
$CREATE COMMENT
Author: Narayan 
Date: Oct 3, 1994.

Description: This is a test to test the auto-commit behavior of IB for DDLs. 

The auto-commit behavior is set using unix sed commands.
We sed the A.c file to insert isc_autocommit in its tpb defintion.

$CREATE init.sql
  create database 'WHERE_GDB:test.gdb';
  create table t ( a int);
  create generator t_gen;
  set generator t_gen to 10;
  set term go;
  create procedure ins as
  declare variable n integer;
  begin
    n = gen_id(t_gen,1);
    insert into t values (:n);
  end go
  set term ;go
  commit;

$CREATE A.e
#include <stdio.h>
exec sql include salca

exec sql set database DB = 'WHERE_GDB:test.gdb';

main()
{
  exec sql connect DB;

  exec sql set transaction;

  exec sql execute immediate 'CREATE GENERATOR T_GEN'; 

  if (SQLCODE) isc_print_status(isc_status);

  exec sql disconnect DB;

  exec sql connect DB;

  exec sql set transaction;

  exec sql execute immediate 'DROP PROCEDURE INS';

  if (SQLCODE) isc_print_status(isc_status);

  exec sql disconnect DB;

}
$CREATE show.sql
 connect 'WHERE_GDB:test.gdb';
 execute procedure ins;
 select * from t;
$ISQL -i init.sql
$GPRE -e  A.e
$RUN sed "/isc_tpb_. \[/s/\[.\] = {1,/\[\] = {1, isc_tpb_autocommit,/" A.c > A1.c
$RUN sed "/isc_start_transaction /s/4/5/" A1.c > A2.c
$CC FLAG_CC A2.c
$LINK FLAG_LINK A2 
$RUN A2
$ISQL -i show.sql
$DELETE COMMENT init.sql show.sql A.* A1.* A2.*
$DROP WHERE_GDB:test.gdb
