
$CREATE COMMENT
Author: Narayan 
Date: Mar 17, 1994.

Description: This is a test to test the auto-commit behavior of IB. 
It creates table t,u & v. Creates an after insert trigger on table t
that also inserts into u and v. It inserts a value into t so the 
trigger causes the further inserts into U and V. Then it does a rollback, but
because of auto-commit on the previous inserts should be committed.

The auto-commit behavior is set using unix sed commands.
We sed the A.c file to insert isc_autocommit in its tpb defintion.

$CREATE init.sql
  create database "WHERE_GDB:ac1_test.gdb";
  create table t (a integer);
  create table u (b integer);
  create table v (c integer);

  commit;
  connect "WHERE_GDB:ac1_test.gdb";
  set term go;
  create trigger trig_ins for t active after insert position 0 as
  begin 
    insert into u values (new.a*10);
    insert into v values (new.a*100);
  end go
  set term ;go

  commit;

$CREATE A.e
#include <stdio.h>
exec sql include salca

exec sql set database DB = "WHERE_GDB:ac1_test.gdb";

main()
{
	exec sql connect DB;

	exec sql set transaction;

	exec sql insert into t values (10);

	if (SQLCODE) isc_print_status(gds__status);

	exec sql rollback;
}

$CREATE show.sql
 connect "WHERE_GDB:ac1_test.gdb";
 select * from t;
 select * from u;
 select * from v;
$ISQL -m -i init.sql
$GPRE -e A.e
$RUN sed "/isc_tpb_0 \[/s/\[.\] = {1,/\[\] = {1, isc_tpb_autocommit,/" A.c > A1.c
$RUN sed "/isc_start_transaction /s/4/5/" A1.c > A2.c
$CC FLAG_CC A2.c
$LINK FLAG_LINK A2 
$RUN A2
$ISQL -m -i show.sql
$DELETE COMMENT init.sql show.sql A.* A1.* A2.*
$DROP WHERE_GDB:ac1_test.gdb
