#
#Author: Narayan
#Date: Oct 3, 1994.
#
#Description: This is a test to test the auto-commit behavior of IB for DDLs.
#
#The auto-commit behavior is set using unix sed commands.
#We sed the A.c file to insert isc_autocommit in its tpb defintion.
#

>> init.sql
  create database 'WHERE_GDB:test.gdb';
  create table t (a integer, b integer);
  create table u (b integer);
  create index t_ind on t(a);
  commit;

>> A.e
#include <stdio.h>
exec sql include salca

exec sql set database DB = 'WHERE_GDB:test.gdb';

int main()
{
  exec sql connect DB;

  exec sql set transaction;

  exec sql execute immediate 'CREATE UNIQUE INDEX T_IND ON T(B)';

  if (SQLCODE) isc_print_status(isc_status);

  exec sql disconnect DB;

  exec sql connect DB;

  exec sql set transaction;

  exec sql insert into t values (10,10);

  if (SQLCODE) isc_print_status(isc_status);

  exec sql disconnect DB;

  exec sql connect DB;

  exec sql set transaction;

  exec sql execute immediate 'DROP INDEX T_IND';

  if (SQLCODE) isc_print_status(isc_status);

  exec sql disconnect DB;

  exec sql connect DB;

  exec sql set transaction;

  exec sql execute immediate 'CREATE UNIQUE INDEX T_IND ON T(B)';

  if (SQLCODE) isc_print_status(isc_status);

  exec sql disconnect DB;

}
>> show.sql
 connect 'WHERE_GDB:test.gdb';
 show index  t_ind;
 insert into t values (10,10);
 insert into t values (10,10);
 commit;
 select * from t;
$ISQL -m -i init.sql
$GPRE -e  A.e
$RUN sed "/isc_tpb_. \[/s/\[.\] = {1,/\[\] = {1, isc_tpb_autocommit,/" A.c > A1.c
$RUN sed "/isc_start_transaction /s/4/5/" A1.c > A2.c
$CC FLAG_CC A2.c
$LINK FLAG_LINK A2
$RUN A2
$ISQL -m -i show.sql
$DELETE init.sql show.sql A.* A1.* A2.* A2
$DROP WHERE_GDB:test.gdb
