
#
#Author: Narayan 
#Date: Mar 17, 1994.
#
#Description: This is a test to test the auto-commit behavior of IB. 
#It creates table t,u & v. Creates procedures ins_t, ins_u and Ins_v. 
#These procedures execute in a chain fashion. The procedure ins_v fails
#and so none of the procedures should commit even if auto-commit is on.
#
#The auto-commit behavior is set using unix sed commands.
#We sed the A.c file to insert isc_autocommit in its tpb defintion.
#

>> init.sql
  create database "WHERE_GDB:ac3_test.gdb";
  create table t (a integer);
  create table u (b integer);
  create table v (c integer);
  create unique index uni_ind on v (c);

  commit;
  connect "WHERE_GDB:ac3_test.gdb";

  set term go;
  create procedure ins_v (x integer) as
  begin
    insert into v values (:x*100);
  SUSPEND;
  end
  go

  create procedure ins_u (x integer) as
  begin
    insert into u values (:x*10);
    execute procedure ins_v :x;
  SUSPEND;
  end
  go

  create procedure ins_t (x integer) as
  begin
    insert into t values (:x);
    execute procedure ins_u :x;
  SUSPEND;
  end
  go
  set term ;go

  insert into v values (1000);
  commit;

>> A.e
#include <stdio.h>
exec sql include salca

exec sql set database DB = "WHERE_GDB:ac3_test.gdb";

main()
{
  exec sql connect DB;

  exec sql set transaction;

  exec sql execute procedure ins_t 10; 

  if (SQLCODE) isc_print_status(gds__status);

  exec sql commit;
}

>> show.sql
 connect "WHERE_GDB:ac3_test.gdb";
 select * from t;
 select * from u;
 select * from v;
$ISQL -m -i init.sql
$GPRE -e A.e
$RUN sed "/isc_tpb_0 \[/s/\[.\] = {1,/\[\] = {1, isc_tpb_autocommit,/" A.c > A1.c
$RUN sed "/isc_start_transaction /s/4/5/" A1.c > A2.c
$CC FLAG_CC A2.c
$LINK FLAG_LINK A2 
$RUN A2
$ISQL -m -i show.sql
$DELETE init.sql show.sql A.* A1.* A2.*
$DROP WHERE_GDB:ac3_test.gdb
