
#/**********************************************************************
# Purpose:		Test predicates support in InterBase SQL 4.0
# 
# Syntax:                <column-spec> [NOT] CONTAINING <value-spec>
#
# Description:           char-field, in a view
#
#                        SELECT DEPTNO
#                        FROM DEPT_BUDGET
#                        WHERE DEPTNO CONTAINING '12';
#
# Tables:                DEPT_BUDGET
#
# Author:                Sam Hakim, Feb 19, 93
# ***********************************************************************

$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
>> con013.e

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON DEPARTMENTS.DEPTNO     DeptNo;


char Test[]="SELECT DEPTNO \
FROM DEPT_BUDGET \
WHERE DEPTNO CONTAINING '12'";

void Underline();

main(argc, argv)
int argc;
char *argv[];

{
	
	int Count = 0;
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT DEPTNO
                FROM DEPT_BUDGET
                WHERE DEPTNO CONTAINING '12';

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :DeptNo;

        while (SQLCODE == 0){
		Count++;

                printf("%s\n",DeptNo);
                Underline(80);

                EXEC SQL
                FETCH CR INTO :DeptNo;

        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e con013.e
$ CC FLAG_CC con013.c
$ LINK FLAG_LINK con013 
$ RUN con013
>> con013.qli
set semicolon;
ready WHERE_GDB:sh_test.gdb;
SELECT DEPTNO
FROM DEPT_BUDGET
WHERE DEPTNO CONTAINING '12';

FOR D IN DEPT_BUDGET WITH D.DEPTNO CONTAINING '12' PRINT D.DEPTNO;
FINISH;
QUIT;

$ QLI -n -a con013.qli
>> con013.sql
connect WHERE_GDB:sh_test.gdb;
SELECT DEPTNO
FROM DEPT_BUDGET
WHERE DEPTNO CONTAINING '12';
quit;
$ISQL -m -i con013.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE con013* 
