
$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
$ CREATE con031.e
/**********************************************************************
 Purpose:		Test predicates support in InterBase SQL 4.0
 
 Syntax:                <column-spec> [NOT] CONTAINING <value-spec>

 Description:           varchar field containing number

                        SELECT EMPNO
                        FROM MANAGEMENT
                        WHERE EMPNO CONTAINING 1;

 View:                  management

 Author:                Sam Hakim, Feb 19, 93
 ***********************************************************************
*/

#include <stdio.h>
#include "WHERE_FILES:sh_test.h"

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON EMPLOYEES.EMPNO        EmpNo;


char Test[]="SELECT EMPNO \
FROM MANAGEMENT \
WHERE EMPNO CONTAINING 1";

void Underline();

main(argc, argv)
int argc;
char *argv[];

{
	
	int verbose, Count;
	Count = 0;

	/*--- check if verbose is requested ------ */
	verbose = FALSE;
	if (--argc > 0){	
		if (*argv[1] == 'v' || *argv[1] == 'V')
			verbose = TRUE;
	}
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT EMPNO
                FROM MANAGEMENT
                WHERE EMPNO CONTAINING 1;

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :EmpNo;

        while (SQLCODE == 0){

                Count++;
                printf("%d\n",EmpNo);
                Underline(80);

                EXEC SQL
                FETCH CR INTO :EmpNo;
        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e con031.e
$ CC FLAG_CC con031.c
$ LINK FLAG_LINK con031 
$ RUN con031
$ CREATE con031.qli
SET SEMICOLON;
ready WHERE_GDB:sh_test.gdb;
SELECT EMPNO
FROM MANAGEMENT
WHERE EMPNO CONTAINING 1;

FOR M IN MANAGEMENT WITH M.EMPNO CONTAINING 1 PRINT M.EMPNO;
finish;
quit;

$ QLI -n -a con031.qli
$ CREATE con031.sql
connect WHERE_GDB:sh_test.gdb;
SELECT EMPNO
FROM MANAGEMENT
WHERE EMPNO CONTAINING 1;
quit;
$ISQL -i con031.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE con031* 
