
$ GBAK -rep sh_blobs.gbk WHERE_GDB:sh_blobs_21.gdb
>> blob021.epp
/**********************************************************************
 Purpose:               Test SQL blob support in InterBase 4.0
 Description:           SET A BLOB TO NULL 
 Author:                Sam Hakim, June 16, 93
 **********************************************************************/
#include <stdio.h>
#include <cstdlib>
#include <cstring>

DATABASE DB = "WHERE_GDB:sh_blobs_21.gdb";
EXEC SQL	INCLUDE SQLCA;
EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;

BASED_ON MB1.TEST_NAME      Test_Name;
BASED_ON MB1.COMMENT        Comment;
BASED_ON MB1.ROW_ID         Row_Id;
BASED_ON MB1.B              BlobId1;
short			    BlobIndNull = -1;

bool verbose;

struct Buf{
    char            *Buffer[5];			/* Buffer vector to store blobs */
    unsigned short  BufferLen[5];		
};
struct Buf M;

char Test[]="Set an existing non-empty blob to NULL";

void Underline(int);

int main(int argc, char* argv[])
{
short                       i,j,k,l;
int Count;

    verbose = false;
    if (--argc > 0){
        if (*argv[1] == 'v' || *argv[1] == 'V')
            verbose = true;
        }

    READY;              /* Bug 4549 will be fixed in verion G */
    START_TRANSACTION;

	
    EXEC SQL DECLARE TCR CURSOR FOR
             SELECT TEST_NAME,ROW_ID,B,COMMENT
             FROM MB1 WHERE ROW_ID =2;

    EXEC SQL OPEN TCR ;
    EXEC SQL FETCH TCR INTO :Test_Name,:Row_Id,:BlobId1,:Comment;

    strcpy(Test_Name,"blob021");

    EXEC SQL UPDATE MB1 SET TEST_NAME = :Test_Name,B=:BlobId1:BlobIndNull,
	     COMMENT = "Blob Nullifier" WHERE CURRENT OF TCR;
    EXEC SQL CLOSE TCR;
    EXEC SQL COMMIT;

FINISH;

exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds_status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/***********************************************************
 * U n d e r l i n e
 * print an underline
 ***********************************************************/
void Underline(int i)
{
int j;
for (j=0;j<i;j++)
	printf("-");
printf("\n");
}

$ GPRE -e blob021.epp
$ CXX FLAG_CXX blob021.cpp
$ LINK FLAG_LINK blob021 
$ RUN blob021
>> blob021.qli
ready WHERE_GDB:sh_blobs_21.gdb;
select test_name, row_id, comment, b from mb1 where test_name = 'blob021' and b is null;
finish;
quit;
$ QLI -n -a blob021.qli
$DROP WHERE_GDB:sh_blobs_21.gdb
$ DELETE blob021*
