
$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
$ CREATE sta008.e
/**********************************************************************
 Purpose:		Test predicates support in InterBase SQL 4.0
 
 Syntax:                <column spec> STARTING [WITH] <value spec>
                        Case sensitive searches including blob string

 Description:           STARTING  - Logical AND, WITH keyword omitted

                        SELECT STATE FROM CUSTOMERS
                        WHERE STATE STARTING 'C' AND STATE NOT IN ('CA');

 Tables:                customers

 Author:                Sam Hakim, Feb 19, 93
 ***********************************************************************
*/

#include <stdio.h>
#include "WHERE_FILES:sh_test.h"

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON CUSTOMERS.STATE        State;

char Test[]="SELECT STATE FROM CUSTOMERS \
WHERE STATE STARTING 'C' AND STATE NOT IN ('CA')";

void Underline();

main(argc, argv)
int argc;
char *argv[];

{
	
	int verbose, Count;
	Count = 0;

	/*--- check if verbose is requested ------ */
	verbose = FALSE;
	if (--argc > 0){	
		if (*argv[1] == 'v' || *argv[1] == 'V')
			verbose = TRUE;
	}
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                        SELECT STATE FROM CUSTOMERS
                        WHERE STATE STARTING 'C' AND STATE NOT IN ('CA');

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :State;

        while (SQLCODE == 0){
		Count++;

                printf("%s\n",State);
                Underline(80);

                EXEC SQL
                        FETCH CR INTO :State;

        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}
$ GPRE -e sta008.e
$ CC FLAG_CC sta008.c
$ LINK FLAG_LINK sta008 
$ RUN sta008
$ CREATE sta008.qli

ready WHERE_GDB:sh_test.gdb;
set semicolon;
SELECT STATE FROM CUSTOMERS WHERE STATE STARTING 'C' AND STATE NOT IN ('CA');
finish;
quit;
$ QLI -n -a sta008.qli
$ CREATE sta008.sql
connect WHERE_GDB:sh_test.gdb;
SELECT STATE FROM CUSTOMERS WHERE STATE STARTING 'C' AND STATE NOT IN ('CA');
quit;
$ISQL -m -i sta008.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE sta008* 
