
#
#HISTORY:
#04-Oct-2001 Neil McCalden 
#Remove field ambiguity which Firebird now checks for.
#

$ GBAK -r WHERE_FILES:sh_join.gbk WHERE_GDB:sh_join_41.gdb
>> join041.e

/**********************************************************************
 Purpose:               Test SQL OUTER JOIN support in InterBase 4.0
 Description:           outer join where column outer join
 Author:                Sam Hakim, June 1, 93
 ***********************************************************************
*/

#include <stdio.h>

DATABASE DB = "WHERE_GDB:sh_join_41.gdb";
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON st1.s1     t1s1;
BASED_ON st1.s2     t1s2;
BASED_ON st1.comp_s t1comp_s;
BASED_ON st1.table_row   t1table_row;

BASED_ON st2.s1     t2s1;
BASED_ON st2.s2     t2s2;
BASED_ON st2.comp_s t2comp_s;
BASED_ON st2.table_row   t2table_row;

char Test[]="\
select t.s1,t.s2,t.comp_s,t.table_row,x.s1,x.s2,x.comp_s,x.table_row \
from (st1 t left outer join st2 x on t.s1 = x.s1) \
where t.s1 > \
(select s1 from (st1 inner join st2 on st1.s2 = st2.s2 and st2.s2= 101)) \
order by t.table_row ascending";

void Underline();

main()
{
	
    int Count;
	Count = 0;
    printf ("Test:\n %s\n",Test);
    Underline(80);

    EXEC SQL
        DECLARE CR CURSOR FOR
        select t.s1,t.s2,t.comp_s,t.table_row,x.s1,x.s2,x.comp_s,x.table_row
        from (st1 t left outer join st2 x on t.s1 = x.s1)
        where t.s1 >
        (select s1 from (st1 inner join st2 on st1.s2 = st2.s2 and st2.s2= 101))
        order by t.table_row ascending;

        EXEC SQL
		OPEN CR;
		
    EXEC SQL    FETCH CR INTO :t1s1,:t1s2,:t1comp_s,:t1table_row,
                :t2s1,:t2s2,:t2comp_s,:t2table_row;

        while (SQLCODE == 0){
		Count++;

                printf("%10d  ",t1s1);
                printf("%10d  ",t1s2);
                printf("%10d  ",t1comp_s);
                printf("%-10s  ",t1table_row);

                printf("%10d  ",t2s1);
                printf("%10d  ",t2s2);
                printf("%10d  ",t2comp_s);
                printf("%-10s\n",t2table_row);

                EXEC SQL
                FETCH CR INTO :t1s1,:t1s2,:t1comp_s,:t1table_row,
                :t2s1,:t2s2,:t2comp_s,:t2table_row;
        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;

exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e join041.e
$ CC FLAG_CC join041.c
$ LINK FLAG_LINK join041 
$ RUN join041
>> join041.sql
connect WHERE_GDB:sh_join_41.gdb;
select t.s1,t.s2,t.comp_s,t.table_row,x.s1,x.s2,x.comp_s,x.table_row
from (st1 t left outer join st2 x on t.s1 = x.s1)
where t.s1 > 
(select st1a.s1 from (st1 st1a inner join st2 st2a on st1a.s2 = st2a.s2 and st2a.s2= 101))
order by t.table_row ascending;
quit;
$ISQL -m -i join041.sql
$DROP WHERE_GDB:sh_join_41.gdb
$ DELETE join041* 
