
#/**********************************************************************
# Purpose:		Test predicates support in InterBase SQL 4.0
#
# Syntax:                <column-spec> [NOT] CONTAINING <value-spec>
#
# Description:           varchar numeric field - long -  containing number
#
#                        SELECT SALARY
#                        FROM MANAGEMENT
#                        WHERE SALARY CONTAINING 1;
#
# View:                  management
#
# Author:                Sam Hakim, Feb 19, 93
# ***********************************************************************

$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
>> con032.e

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON EMPLOYEES.SALARY       Salary;


char Test[]="SELECT SALARY \
FROM MANAGEMENT \
WHERE SALARY CONTAINING 1";

void Underline();

int main(argc, argv)
int argc;
char *argv[];

{
	int Count = 0;
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT SALARY
                FROM MANAGEMENT
                WHERE SALARY CONTAINING 1;

        EXEC SQL
		OPEN CR;

	EXEC SQL
                FETCH CR INTO :Salary;

        while (SQLCODE == 0){

                Count++;
                printf("%8.2f\n",(double)(Salary/100));
                Underline(80);

                EXEC SQL
                FETCH CR INTO :Salary;
        }

NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


return 0;

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	return 1;
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e con032.e
$ CC FLAG_CC con032.c
$ LINK FLAG_LINK con032
$ RUN con032
>> con032.sql
connect WHERE_GDB:sh_test.gdb;
SELECT SALARY
FROM MANAGEMENT
WHERE SALARY CONTAINING 1;
quit;
$ISQL -m -i con032.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE con032*
