
$ GBAK -rep sh_blobs.gbk WHERE_GDB:sh_blobs_13.gdb
>> blob013.epp
/**********************************************************************
 Purpose:               Test SQL blob support in InterBase 4.0
 Description:           INSERT CURSOR - BufferLen < 0 
 Author:                Sam Hakim, June 7, 93
 Note:			Sent a message to Norm regarding this core 
			dumping on 6/11/93.  Awaiting response.
 			Norm responded: -1 unsigned short means 
			65535 bytes(2's complement).

			This test was purposely put in because the user
			might easily be traped into this situation.
 **********************************************************************/
#include <stdio.h>
#include <cstdlib>
#include <cstring>

using namespace std;

DATABASE DB = "WHERE_GDB:sh_blobs_13.gdb";
EXEC SQL	INCLUDE SQLCA;
EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;

BASED_ON MB1.TEST_NAME      Test_Name;
BASED_ON MB1.COMMENT        Comment;
BASED_ON MB1.ROW_ID         Row_Id;
BASED_ON MB1.B512           BlobId;

bool verbose;

struct Buf{
    char   Buffer[50];
    short  BufferLen;
};
struct Buf M;

char Test[]="INSERT BLOB-CURSOR VALUES (Buffer,-1) - Buffer length<0 \n \
             Bufferlen<0 produces core dumps and not allowed. \n \
	     BufferLen type should be unsigned short";	

void Underline(int);
void CreateLine(char Bf[],int L);
void EmptyBuffer(char *Bf,int L);

int main(int argc,char* argv[])
{
short                       i,j,k,l;
int Count;

    verbose = false;
    if (--argc > 0){
        if (*argv[1] == 'v' || *argv[1] == 'V')
            verbose = true;
        }

    READY;              /* Bug 4549 will be fixed in verion G */
   
    Count = 0;
    M.Buffer[0] = 0;
    /* strcpy(Test_Name,"blob013"); */
    printf ("Test:\n %s\n",Test);
    Underline(80);

    EXEC SQL
    DECLARE BCW CURSOR FOR
    INSERT BLOB B512 INTO MB1;

    for (j = 12; j < 13; j++){
        START_TRANSACTION;  /* and these lines should be deleted */
        EXEC SQL
        OPEN BCW INTO :BlobId;      /* This will change in G to INTO */

        for (i=1; i<5; i++){
	    printf("A signed short for buff len < 0 produces core dump\n");
            sprintf (M.Buffer,"Line: %d>",i);
            CreateLine(M.Buffer,sizeof(M.Buffer));
            /* M.BufferLen = -1; */
	    /* Note: This program will core dump and produce diff result
		     each time it is run when M.BufferLen is <0.
		     So It was changed to print out a message instead. */
            EXEC SQL
                INSERT CURSOR BCW VALUES (:M.Buffer:M.BufferLen);
	   	  if (verbose)
		      printf("SQLCODE %d, BufferLen %d \n",SQLCODE,M.BufferLen);
            EmptyBuffer(M.Buffer,sizeof(M.Buffer));
        }
	EmptyBuffer(M.Buffer,sizeof(M.Buffer));
	sprintf (M.Buffer,"Line: %d> --- End of BLOB B512 ---",i);
	EXEC SQL
                INSERT CURSOR BCW VALUES (:M.Buffer:M.BufferLen);
    EXEC SQL
        CLOSE BCW;
    EXEC SQL
        INSERT INTO MB1 (TEST_NAME,ROW_ID,B512) VALUES (:Test_Name,:j,:BlobId);
    EXEC SQL COMMIT;
    }

FINISH;

exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds_status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/************************************************************
 * Draw and underline
 ************************************************************/
void Underline(int i)
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}
/***********************************************************
 * EmptyBuffer
 * print an underline
 ***********************************************************/
void EmptyBuffer(char *Bf,int L)
{
char *s;
for (s=Bf;L;L--)
	*s++ = ' ';
}
/************************************************************
 * Create a new line for the blob content.
 ************************************************************/
void CreateLine(char Bf[],int L)
{
char      TempBuf[4],*s;
int	  i,j,t,k;

     
     t = sizeof(TempBuf);
     j = 0;

     for (i = 9; i < L; i+=t){
	j++;
	sprintf (TempBuf,"%d,",j);
	strncat(Bf,TempBuf,t); 
     }
	strncat(Bf,"<EOL",5);
if (verbose)
	printf("%s\n",Bf);
}

$ GPRE -e blob013.epp
$ CXX FLAG_CXX blob013.cpp
$ LINK FLAG_LINK blob013 
$ RUN blob013
>> blob013.qli
ready WHERE_GDB:sh_blobs_13.gdb;
select test_name, row_id, b512 from mb1 where test_name = 'blob013';
finish;
quit;
$ QLI -n -a blob013.qli
$DROP WHERE_GDB:sh_blobs_13.gdb
$ DELETE blob013*
