
#/**********************************************************************
# Purpose:		Test predicates support in InterBase SQL 4.0
# 
# Syntax:                <column-spec> [NOT] CONTAINING <value-spec>
#
# Description:           char-field, concatenated field
#
#                        SELECT NAME
#                        FROM EMPLOYEES
#                        WHERE NAME CONTAINING 'z'
#
# Tables:                employees
#
# Author:                Sam Hakim, Feb 19, 93
# ***********************************************************************

$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
>> con010.e

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON EMPLOYEES.NAME         Name;


char Test[]="SELECT NAME \
FROM EMPLOYEES \
WHERE NAME CONTAINING 'z'";

void Underline();

main(argc, argv)
int argc;
char *argv[];

{
	
	int Count = 0;
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT NAME
                FROM EMPLOYEES
                WHERE NAME CONTAINING 'z';

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :Name;

        while (SQLCODE == 0){
		Count++;

                printf("%s\n",Name);
                Underline(80);

                EXEC SQL
                        FETCH CR INTO :Name;

        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e con010.e
$ CC FLAG_CC con010.c
$ LINK FLAG_LINK con010 
$ RUN con010
>> con010.qli
set semicolon;
ready WHERE_GDB:sh_test.gdb;
SELECT NAME
FROM EMPLOYEES
WHERE NAME CONTAINING 'z';

FOR E IN EMPLOYEES WITH E.NAME CONTAINING 'z' PRINT NAME;
FINISH;
QUIT;
$ QLI -n -a con010.qli
>> con010.sql
SELECT NAME
FROM EMPLOYEES
WHERE NAME CONTAINING 'z';
quit;
$ISQL -m WHERE_GDB:sh_test.gdb -i con010.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE con010* 
