
$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
$ CREATE con008.e
/**********************************************************************
 Purpose:		Test predicates support in InterBase SQL 4.0
 
 Syntax:                <column-spec> [NOT] CONTAINING <value-spec>

 Description:           char-field, containing an empty string ""

                        SELECT JOB
                        FROM EMPLOYEES
                        WHERE JOB CONTAINING ''
                        ORDER BY JOB ASCENDING;

 Tables:                employees

 Author:                Sam Hakim, Feb 19, 93
 ***********************************************************************
*/

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON EMPLOYEES.JOB          Job;


char Test[]="SELECT JOB \
FROM EMPLOYEES \
WHERE JOB CONTAINING '' \
ORDER BY JOB ASCENDING";

void Underline();

main(argc, argv)
int argc;
char *argv[];

{
	
	int Count = 0;
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT JOB
                FROM EMPLOYEES
                WHERE JOB CONTAINING ""
                ORDER BY JOB ASCENDING;

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :Job;

        while (SQLCODE == 0){
		Count++;

                printf("%s\n",Job);
                Underline(80);

                EXEC SQL
                        FETCH CR INTO :Job;

        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e con008.e
$ CC FLAG_CC con008.c
$ LINK FLAG_LINK con008 
$ RUN con008
$ CREATE con008.qli
set semicolon;
ready WHERE_GDB:sh_test.gdb;
SELECT JOB
FROM EMPLOYEES
WHERE JOB CONTAINING ""
ORDER BY JOB ASCENDING;

FOR E IN EMPLOYEES SORTED BY ASCENDING E.JOB WITH E.JOB CONTAINING "" PRINT E.JOB;
finish;
quit;
$ QLI -n -a con008.qli
$ CREATE con008.sql
connect WHERE_GDB:sh_test.gdb;
SELECT JOB
FROM EMPLOYEES
WHERE JOB CONTAINING ""
ORDER BY JOB ASCENDING;
quit;
$ISQL -m -i con008.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE con008* 
