
$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
$ CREATE sin020.e
/**********************************************************************
 Purpose:		Test predicates support in InterBase SQL 4.0
 Syntax:                [NOT] SINGULAR <subquery>
 Description:           SINGULAR - using views

                        SELECT *
                        FROM DEPT_BUDGET V1
                        WHERE SINGULAR
                        (SELECT *
                        FROM FULLEMP
                        V2 WHERE V2.DEPARTMENT = V1.DEPARTMENT);

 Tables:                customers
 Author:                Sam Hakim, Feb 19, 1993
 ***********************************************************************
*/

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON DEPARTMENTS.DEPTNO             DeptNo;
BASED_ON DEPARTMENTS.DEPARTMENT         Department;
BASED_ON DEPARTMENTS.MGRNO              MgrNo;
BASED_ON DEPARTMENTS.REPORTS            Reports;
BASED_ON JOBS.LEVEL                     Level;
BASED_ON DEPARTMENTS.HEAD_DEPT          Head_Dept;
BASED_ON JOBS.HIGH_SALARY_RANGE         Budget;

void Underline();
void pad();


char Test[]="SELECT * \
FROM DEPT_BUDGET V1 \
WHERE SINGULAR \
(SELECT * \
FROM FULLEMP \
V2 WHERE V2.DEPARTMENT = V1.DEPARTMENT)";

void Underline();
main(argc, argv)
int argc;
char *argv[];

{
	
	int Count = 0;
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT *
                FROM DEPT_BUDGET V1
                WHERE SINGULAR
                (SELECT *
                FROM FULLEMP
                V2 WHERE V2.DEPARTMENT = V1.DEPARTMENT);

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :DeptNo,:Department,:MgrNo,:Reports,
                :Level,:Head_Dept,:Budget;

        while (SQLCODE == 0){
		Count++;
                pad(Department, sizeof(Department));
                pad(Level,sizeof(Level));
                pad(Head_Dept,sizeof(Head_Dept));

                printf("%s\t",DeptNo);
                printf("%s\t",Department);
                printf("%d\t",MgrNo);
                printf("%d\t",Reports);
                printf("%s\t",Level);
                printf("%s\t",Head_Dept);
                printf("%8.2f\n",(double)((Budget)/100));
		Underline(80);	

                EXEC SQL
                FETCH CR INTO :DeptNo,:Department,:MgrNo,:Reports,
                :Level,:Head_Dept,:Budget;
        }
	
NOMORE:

	EXEC SQL
		CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR:    EXEC SQL
                CLOSE CR;

	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

/***************************************************************
 * pad the character string with blanks
 ***************************************************************
*/
void pad(string,l)
char *string;
int l;
{

char *s;
int i;

i = 1;
s = string;

while (*s){
	s++;
	i++;
}

for (;i<l;s++,i++)
	*s=' ';	
*s='\0';
}

$ GPRE -e sin020.e
$ CC FLAG_CC sin020.c
$ LINK FLAG_LINK sin020 
$ RUN sin020
$ CREATE sin020.qli
ready WHERE_GDB:sh_test.gdb;
set semicolon;
select * from dept_budget v1 where singular (select * from fullemp
v2 where v2.department = v1.department);
 
select * from dept_budget v1 where 1 =  (select count(*) from fullemp
v2 where v2.department = v1.department); 

finish;
quit;
$ QLI -n -a sin020.qli
$ CREATE sin020.sql
connect WHERE_GDB:sh_test.gdb;
select * from dept_budget v1 where singular (select * from fullemp
v2 where v2.department = v1.department);
 
select * from dept_budget v1 where 1 =  (select count(*) from fullemp
v2 where v2.department = v1.department); 
quit;
$ISQL -m -i sin020.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE sin020* 

