
#
#23-Apr-04 Changed the order of nulls according to SQL standard
#

$ GBAK -r WHERE_FILES:sh_join.gbk WHERE_GDB:sh_join_15.gdb
>> join015.e

/**********************************************************************
 Purpose:               Test SQL OUTER JOIN support in InterBase 4.0
 Description:           GROUP BY clause on joined table
 Author:                Sam Hakim, June 1, 93
 ***********************************************************************
*/

#include <stdio.h>

DATABASE DB = "WHERE_GDB:sh_join_15.gdb";
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON st5.s1      t1s1;
BASED_ON st5.s1      sums1;

char Test[]="\
select sum(x.s1), x.s1 \
from (st5 x left join st2 y on x.s1 = y.s1) \
group by x.s1";

void Underline();

int main()
{

    int Count;
	Count = 0;
    printf ("Test:\n %s\n",Test);
    Underline(80);

    EXEC SQL
                DECLARE CR CURSOR FOR
                select sum(x.s1), x.s1
                from (st5 x left join st2 y on x.s1 = y.s1)
                group by x.s1;

        EXEC SQL
		OPEN CR;

	EXEC SQL
                FETCH CR INTO :sums1,:t1s1;


        while (SQLCODE == 0){
		Count++;

                printf("%d     ",sums1);
                printf("%d\n",t1s1);

                EXEC SQL
                FETCH CR INTO :sums1,:t1s1;

        }

NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


return 0;

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	return 1;
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e join015.e
$ CC FLAG_CC join015.c
$ LINK FLAG_LINK join015
$ RUN join015
>> join015.sql
connect WHERE_GDB:sh_join_15.gdb;
select sum(x.s1), x.s1
from (st5 x left join st2 y on x.s1 = y.s1)
group by x.s1;
quit;
$ISQL -m -i join015.sql
$DROP WHERE_GDB:sh_join_15.gdb
$ DELETE join015*

