
#
#**********************************************************************
# Purpose:		Test predicates support in InterBase SQL 4.0
# Syntax:                <column-spec> [NOT] CONTAINING <value-spec>
# Description:           DELETE ... where field containing <value>
#			DELETE FROM CUSTOMERS
#			WHERE CUSTOMER CONTAINING "'";
#
# Table:                 CUSTOMERS
#
# Author:                Sam Hakim, Feb 19, 93
# ***********************************************************************
#

$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
>> con039.e

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;

EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON CUSTOMERS.CUSTOMER     Name;
BASED_ON CUSTOMERS.ZIP_CODE	Zip;



char Test[]="DELETE FROM CUSTOMERS \
WHERE CUSTOMER CONTAINING ' ";

void Underline();

int main(argc, argv)
int argc;
char *argv[];

{
	int Count = 0;
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
		DELETE FROM CUSTOMERS
		WHERE CUSTOMER CONTAINING "'";

	EXEC SQL
		COMMIT;

	EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT CUSTOMER, ZIP_CODE
                FROM CUSTOMERS
                WHERE CUSTOMER CONTAINING "'";

        EXEC SQL
		OPEN CR;

	EXEC SQL
                FETCH CR INTO :Name,:Zip;

        while (SQLCODE == 0){

                Count++;
                printf("%s %s\n",Name,Zip);
                Underline(80);

                EXEC SQL
                        FETCH CR INTO :Name,:Zip;
        }

NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


return 0;

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	return 1;
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e con039.e
$ CC FLAG_CC con039.c
$ LINK FLAG_LINK con039
$ RUN con039
>> con039.sql
connect WHERE_GDB:sh_test.gdb;
select count(*) from customers where customer containing "'";
quit;
$ISQL -m -i con039.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE con039*

