#
#**********************************************************************
# Purpose:		Test predicates support in InterBase SQL 4.0
# Syntax:		[NOT]SINGULAR <subquery>
# Description:           Two table joins in subquery - SINGULAR
#
#                        SELECT T1.EMPNO,T1.LAST_NAME, T1.FIRST_NAME
#                        FROM SALES_PEOPLE T1 WHERE SINGULAR
#                        (SELECT * FROM SALES T3 , EMPLOYEES T2 WHERE
#                        T3.SALES_REP = T1.EMPNO AND T3.TOTAL_VALUE > 6000
#                        AND T3.SALES_REP = T2.EMPNO);
#
# Tables:                sales_people, employees, sales
# Author:                Sam Hakim, Feb 19, 1993
# ***********************************************************************
#

$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
>> sin009.e

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON SALES_PEOPLE.EMPNO             EmpNo;
BASED_ON SALES_PEOPLE.LAST_NAME         Last_Name;
BASED_ON SALES_PEOPLE.FIRST_NAME        First_Name;


char Test[]="SELECT T1.EMPNO,T1.LAST_NAME, T1.FIRST_NAME \
FROM SALES_PEOPLE T1 WHERE SINGULAR \
(SELECT * FROM SALES T3 , EMPLOYEES T2 WHERE \
T3.SALES_REP = T1.EMPNO AND T3.TOTAL_VALUE > 6000 \
AND T3.SALES_REP = T2.EMPNO)";

void Underline();

int main(argc, argv)
int argc;
char *argv[];

{
	int Count = 0;
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT T1.EMPNO,T1.LAST_NAME, T1.FIRST_NAME
                FROM SALES_PEOPLE T1 WHERE SINGULAR
                (SELECT * FROM SALES T3 , EMPLOYEES T2 WHERE
                T3.SALES_REP = T1.EMPNO AND T3.TOTAL_VALUE > 6000
                AND T3.SALES_REP = T2.EMPNO);

        EXEC SQL
		OPEN CR;

	EXEC SQL
                FETCH CR INTO :EmpNo,:Last_Name,:First_Name

        while (SQLCODE == 0){
		Count++;

                printf("%d\t",EmpNo);
                printf("%s\t",Last_Name);
                printf("%s\n",First_Name);
                Underline(80);

                EXEC SQL
                FETCH CR INTO :EmpNo,:Last_Name,:First_Name

        }

NOMORE:
	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


return 0;

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	return 1;
}

/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e sin009.e
$ CC FLAG_CC sin009.c
$ LINK FLAG_LINK sin009
$ RUN sin009
>> sin009.sql
connect WHERE_GDB:sh_test.gdb;
select t1.empno,t1.last_name, t1.first_name
from sales_people t1 where singular
(select * from sales t3 , employees t2 where
t3.sales_rep = t1.empno and t3.total_value > 6000 and t3.sales_rep = t2.empno);

select t1.empno,t1.last_name, t1.first_name
from sales_people t1 where 1 =
(select count(*) from sales t3 , employees t2 where
t3.sales_rep = t1.empno and t3.total_value > 6000 and t3.sales_rep = t2.empno);
quit;
$ISQL -m -i sin009.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE sin009*

