
$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
$ CREATE con011.e
/**********************************************************************
 Purpose:		Test predicates support in InterBase SQL 4.0
 
 Syntax:                <column-spec> [NOT] CONTAINING <value-spec>

 Description:           char-field, edited field

                        SELECT PROJ_NO, PROJ_NAME
                        FROM PROJECTS
                        WHERE PROJ_NO CONTAINING '3';

 Tables:                projects

 Author:                Sam Hakim, Feb 19, 93
 ***********************************************************************
*/

#include <stdio.h>
#include "WHERE_FILES:sh_test.h"

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON PROJECTS.PROJ_NO               Proj_No;
BASED_ON PROJECTS.PROJ_NAME		Proj_Name;



char Test[]="SELECT PROJ_NO, PROJ_NAME \
FROM PROJECTS \
WHERE PROJ_NO CONTAINING '3'";

void Underline();

main(argc, argv)
int argc;
char *argv[];

{
	
	int verbose, Count;
	Count = 0;

	/*--- check if verbose is requested ------ */
	verbose = FALSE;
	if (--argc > 0){	
		if (*argv[1] == 'v' || *argv[1] == 'V')
			verbose = TRUE;
	}
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT PROJ_NO, PROJ_NAME
                FROM PROJECTS
                WHERE PROJ_NO CONTAINING '3';

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :Proj_No,:Proj_Name;

        while (SQLCODE == 0){
		Count++;

                printf("%s\t",Proj_No);
		printf("%s\n",Proj_Name);
                Underline(80);

                EXEC SQL
                        FETCH CR INTO :Proj_No,:Proj_Name;

        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e con011.e
$ CC FLAG_CC con011.c
$ LINK FLAG_LINK con011 
$ RUN con011
$ CREATE con011.qli
Set semicolon;
ready WHERE_GDB:sh_test.gdb;
SELECT PROJ_NO, PROJ_NAME
FROM PROJECTS
WHERE PROJ_NO CONTAINING '3';

FOR P IN PROJECTS WITH P.PROJ_NO CONTAINING '3' PRINT P.PROJ_NO, P.PROJ_NAME;
FINISH;
QUIT;

$ QLI -n -a con011.qli
$ CREATE con011.sql
connect WHERE_GDB:sh_test.gdb;
SELECT PROJ_NO, PROJ_NAME
FROM PROJECTS
WHERE PROJ_NO CONTAINING '3';
quit;
$ISQL -m -i con011.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE con011* 
