
$ GBAK -r sh_blobs.gbk WHERE_GDB:sh_blobs_21.gdb
$ CREATE blob021.e
/**********************************************************************
 Purpose:               Test SQL blob support in InterBase 4.0
 Description:           SET A BLOB TO NULL 
 Author:                Sam Hakim, June 16, 93
 **********************************************************************/
#include <stdio.h>
#include "WHERE_FILES:sh_test.h"

DATABASE DB = "WHERE_GDB:sh_blobs_21.gdb";
EXEC SQL	INCLUDE SQLCA;
EXEC SQL
        WHENEVER SQLERROR GO TO ERR;

BASED_ON MB1.TEST_NAME      Test_Name;
BASED_ON MB1.COMMENT        Comment;
BASED_ON MB1.ROW_ID         Row_Id;
BASED_ON MB1.B              BlobId1;
short			    BlobIndNull = -1;

int verbose;

struct Buf{
    char            *Buffer[5];			/* Buffer vector to store blobs */
    unsigned short  BufferLen[5];		
};
struct Buf M;

char Test[]="Set an existing non-empty blob to NULL";

void Underline();

main(argc,argv)
int argc;
char *argv[];
{
short                       i,j,k,l;
int Count;

    verbose = FALSE;
    if (--argc > 0){
        if (*argv[1] == 'v' || *argv[1] == 'V')
            verbose = TRUE;
        }

    READY;              /* Bug 4549 will be fixed in verion G */
    START_TRANSACTION;

	
    EXEC SQL DECLARE TCR CURSOR FOR
             SELECT TEST_NAME,ROW_ID,B,COMMENT
             FROM MB1 WHERE ROW_ID =2;

    EXEC SQL OPEN TCR ;
    EXEC SQL FETCH TCR INTO :Test_Name,:Row_Id,:BlobId1,:Comment;

    strcpy(Test_Name,"blob021");

    EXEC SQL UPDATE MB1 SET TEST_NAME = :Test_Name,B=:BlobId1:BlobIndNull,
	     COMMENT = "Blob Nullifier" WHERE CURRENT OF TCR;
    EXEC SQL CLOSE TCR;
    EXEC SQL COMMIT;

FINISH;

exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/***********************************************************
 * U n d e r l i n e
 * print an underline
 ***********************************************************/
void Underline(i)
int i;
{
int j;
for (j=0;j<i;j++)
	printf("-");
printf("\n");
}

$ GPRE -e blob021.e
$ CC FLAG_CC blob021.c
$ LINK FLAG_LINK blob021 
$ RUN blob021
$ CREATE blob021.qli
ready WHERE_GDB:sh_blobs_21.gdb;
select test_name, row_id, comment, b from mb1 where test_name = 'blob021' and b is null;
finish;
quit;
$ QLI -n -a blob021.qli
$DROP WHERE_GDB:sh_blobs_21.gdb
$ DELETE blob021*
