
$ GBAK -r WHERE_FILES:sh_join.gbk WHERE_GDB:sh_join_32.gdb
$ CREATE join032.e

/**********************************************************************
 Purpose:               Test SQL OUTER JOIN support in InterBase 4.0
 Description:           arithmatic expression in select list items
 Author:                Sam Hakim, June 1, 93
 ***********************************************************************
*/

#include <stdio.h>
#include "WHERE_FILES:sh_test.h"

DATABASE DB = "WHERE_GDB:sh_join_32.gdb";
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON CT1.TABLE_ROW      t1Table_Row,t2Table_Row;
short       t1s1, t1s2,t1s3;
short       t2s1, t2s2;



char Test[]="\
select t.s1/1,t.s2*10,t.s3*(-10),t.table_row,x.s1*1,x.s2,x.table_row \
from (st1 t left join st2 x on t.s1 = x.s1)";

void Underline();

main()
{
	
    int Count;
	Count = 0;
    printf ("Test:\n %s\n",Test);
    Underline(80);

    EXEC SQL
        DECLARE CR CURSOR FOR
        select t.s1/1,t.s2*10,t.s3*(-10),t.table_row,x.s1*1,x.s2,x.table_row
        from (st1 t left join st2 x on t.s1 = x.s1);

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :t1s1,:t1s2,:t1s3,:t1Table_Row,
                :t2s1,:t2s2,:t2Table_Row;

        while (SQLCODE == 0){
		Count++;

                printf("%10d  ",t1s1);
                printf("%10d  ",t1s2);
                printf("%10d  ",t1s3);
                printf("%-10s  ",t1Table_Row);


                printf("%10d  ",t2s1);
                printf("%10d  ",t2s2);
                printf("%-10s\n",t2Table_Row);

                EXEC SQL
                FETCH CR INTO :t1s1,:t1s2,:t1s3,:t1Table_Row,
                :t2s1,:t2s2,:t2Table_Row;
        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;

exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}
$ GPRE -e join032.e
$ CC FLAG_CC join032.c
$ LINK FLAG_LINK join032 
$ RUN join032
$ CREATE join032.qli
ready WHERE_GDB:sh_join_32.gdb;
set semicolon;
set columns 100;

select t.s1/1,t.s2*10,t.s3*(-10),t.table_row,x.s1*1,x.s2,x.table_row
from (st1 t left join st2 x on t.s1 = x.s1);
finish;
quit;
$ QLI -n -a join032.qli
$ CREATE join032.sql
connect WHERE_GDB:sh_join_32.gdb;
select t.s1/1,t.s2*10,t.s3*(-10),t.table_row,x.s1*1,x.s2,x.table_row
from (st1 t left join st2 x on t.s1 = x.s1);
quit;
$ISQL -m -i join032.sql
$DROP WHERE_GDB:sh_join_32.gdb
$ DELETE join032* 
