
$ GBAK -r WHERE_FILES:sh_join.gbk WHERE_GDB:sh_join_23.gdb
>> join023.e

/**********************************************************************
 Purpose:               Test SQL OUTER JOIN support in InterBase 4.0
 Description:           WHERE EXISTS (sub-query) - 3 table join
 Author:                Sam Hakim, June 1, 93
 ***********************************************************************
*/

#include <stdio.h>

DATABASE DB = "WHERE_GDB:sh_join_23.gdb";
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON st1.s1     t1s1;
BASED_ON st1.s2     t1s2;
BASED_ON st1.table_row   t1table_row;

BASED_ON st2.s1     t2s1;
BASED_ON st2.s2     t2s2;
BASED_ON st2.table_row   t2table_row;

BASED_ON st3.s1     t3s1;
BASED_ON st3.s2     t3s2;
BASED_ON st3.table_row   t3table_row;

char Test[]="\
select x.s1,x.s2,x.table_row,y.s1,y.s2,y.table_row,z.s1,z.s2,z.table_row \
from (st1 x left join st2 y on x.s1 = y.s1) left join st3 z on z.s1 = y.s1 \
where exists \
(select a.s1 from \
(st1 a left join st2 b on a.s1 = b.s1) left join st3 c on c.s1 = b.s1 and c.s1 = 1)";

void Underline();

main()
{
	
    int Count;
	Count = 0;
    printf ("Test:\n %s\n",Test);
    Underline(80);

    EXEC SQL
                DECLARE CR CURSOR FOR
                select x.s1,x.s2,x.table_row,y.s1,y.s2,y.table_row,z.s1,z.s2,z.table_row
                from (st1 x left join st2 y on x.s1 = y.s1) left join st3 z on z.s1 = y.s1
                where exists
                (select * from
                (st1 a left join st2 b on a.s1 = b.s1) left join st3 c on c.s1 = b.s1 and c.s1 = 1);

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :t1s1,:t1s2,:t1table_row,
                :t2s1,:t2s2,:t2table_row,
                :t3s1,:t3s2,:t3table_row;

        while (SQLCODE == 0){
		Count++;

                printf("%5d   ",t1s1);
                printf("%5d   ",t1s2);
                printf("%-10s   ",t1table_row);

                printf("%5d   ",t2s1);
                printf("%5d   ",t2s2);
                printf("%-10s   ",t2table_row);
		
                printf("%5d   ",t3s1);
                printf("%5d   ",t3s2);
                printf("%-10s\n",t3table_row);

                EXEC SQL
                FETCH CR INTO :t1s1,:t1s2,:t1table_row,
                :t2s1,:t2s2,:t2table_row,
                :t3s1,:t3s2,:t3table_row;
        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;

exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}
$ GPRE -e join023.e
$ CC FLAG_CC join023.c
$ LINK FLAG_LINK join023 
$ RUN join023
>> join023.sql
connect WHERE_GDB:sh_join_23.gdb;
select x.s1,x.s2,x.table_row,y.s1,y.s2,y.table_row,z.s1,z.s2,z.table_row
from (st1 x left join st2 y on x.s1 = y.s1) left join st3 z on z.s1 = y.s1 
where exists
(select a.s1 from 
(st1 a left join st2 b on a.s1 = b.s1) left join st3 c on c.s1 = b.s1 and c.s1 = 1);
quit;
$ISQL -m -i join023.sql
$DROP WHERE_GDB:sh_join_23.gdb
$ DELETE join023* 
