
$ GBAK -r WHERE_FILES:sh_join.gbk WHERE_GDB:sh_join_7.gdb
>> join007.e
/**********************************************************************
 Purpose:               Test SQL OUTER JOIN support in InterBase 4.0
 Description:           INNER JOIN - Syntax check
 Author:                Sam Hakim, June 1, 93
 ***********************************************************************
*/

#include <stdio.h>

DATABASE DB = "WHERE_GDB:sh_join_7.gdb";
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON ct1.c1      t1c1;
BASED_ON ct1.c10     t1c10;
BASED_ON ct1.table_row   t1table_row;
BASED_ON ct2.c1      t2c1;
BASED_ON ct2.c10     t2c10;
BASED_ON ct2.table_row   t2table_row;

char Test[]="\
select t1.c1,t1.c10,t1.table_row,t2.c1,t2.c10,t2.table_row \
from ct1 t1 inner join ct2 t2 on t1.c1 = t2.c1";

void Underline();

main()
{
	
    int Count;
	Count = 0;
    printf ("Test:\n %s\n",Test);
    Underline(80);

    EXEC SQL
                DECLARE CR CURSOR FOR
                select t1.c1,t1.c10,t1.table_row,t2.c1,t2.c10,t2.table_row
                from ct1 t1 inner join ct2 t2 on t1.c1 = t2.c1;

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :t1c1,:t1c10,:t1table_row,:t2c1,:t2c10,:t2table_row;

        while (SQLCODE == 0){
		Count++;

                printf("%-10s",t1c1);
                printf("%-10s",t1c10);
                printf("%-10s",t1table_row);
                printf("%-10s",t2c1);
                printf("%-10s",t2c10);
                printf("%-10s\n",t2table_row);
		
                EXEC SQL
                FETCH CR INTO :t1c1,:t1c10,:t1table_row,:t2c1,:t2c10,:t2table_row;
        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e join007.e
$ CC FLAG_CC join007.c
$ LINK FLAG_LINK join007 
$ RUN join007
>> join007.qli
ready WHERE_GDB:sh_join_7.gdb;
set semicolon;
set columns 100;
select t1.c1,t1.c10,t1.table_row,t2.c1,t2.c10,t2.table_row 
from ct1 t1 inner join ct2 t2 on t1.c1 = t2.c1;
finish;
quit;
$ QLI -n -a join007.qli
>> join007.sql
connect WHERE_GDB:sh_join_7.gdb;
select t1.c1,t1.c10,t1.table_row,t2.c1,t2.c10,t2.table_row 
from ct1 t1 inner join ct2 t2 on t1.c1 = t2.c1;
quit;
$ISQL -m -i join007.sql
$DROP WHERE_GDB:sh_join_7.gdb
$ DELETE join007*
