
#/**********************************************************************
# Purpose:		Test predicates support in InterBase SQL 4.0
#
# Syntax:                <column spec> STARTING [WITH] <value spec>
#                        Case sensitive searches including blob string
#
# Description:           STARTING WITH '' - empty string
#
#                        SELECT JOB
#                        FROM EMPLOYEES
#                        WHERE JOB STARTING WITH ''
#                        ORDER BY JOB ASCENDING;
#
# Tables:                employees
#
# Author:                Sam Hakim, Feb 19, 93
# ***********************************************************************

$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
>> sta009.e

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON EMPLOYEES.JOB          Job;

char Test[]="SELECT JOB \
FROM EMPLOYEES \
WHERE JOB STARTING WITH '' \
ORDER BY JOB ASCENDING";

void Underline();

int main(argc, argv)
int argc;
char *argv[];

{
	int Count = 0;
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                        SELECT JOB
                        FROM EMPLOYEES
                        WHERE JOB STARTING WITH ''
                        ORDER BY JOB ASCENDING;

        EXEC SQL
		OPEN CR;

	EXEC SQL
                FETCH CR INTO :Job;

        while (SQLCODE == 0){
		Count++;

                printf("%s\n",Job);
                Underline(sizeof(Job));

                EXEC SQL
                        FETCH CR INTO :Job;

        }

NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


return 0;

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	return 1;
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}
$ GPRE -e sta009.e
$ CC FLAG_CC sta009.c
$ LINK FLAG_LINK sta009
$ RUN sta009
>> sta009.sql
connect WHERE_GDB:sh_test.gdb;
SELECT JOB FROM EMPLOYEES WHERE JOB STARTING WITH '' ORDER BY JOB ASCENDING;
select count(*) from employees where job starting with '';
quit;
$ISQL -m -i sta009.sql
$ DROP WHERE_GDB:sh_test.gdb
$ DELETE sta009*
