
$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
$ CREATE sin007.e
/**********************************************************************
 Purpose:		Test predicates support in InterBase SQL 4.0
 Syntax:		[NOT]SINGULAR <subquery>			
 Description:           Nested subqueries - SINGULAR

                        SELECT T1.EMPNO,T1.LAST_NAME, T1.FIRST_NAME
                        FROM SALES_PEOPLE T1 WHERE SINGULAR
                        (SELECT * FROM SALES T2 WHERE T1.EMPNO=T2.SALES_REP
                        AND T2.TOTAL_VALUE > 6000 AND EXISTS
                        (SELECT * FROM CUSTOMERS T3)) AND SINGULAR
                        (SELECT * FROM SALES_PERF T4 WHERE T4.EMPNO = T1.EMPNO);

 Tables:                sales, customers (many-to-one relationship)
 Author:		Sam Hakim, Feb 18, 93

 Bugs:			BugNo. 4593: EXIST (sub-query) without where clause
			does not get complete answer set.
 ***********************************************************************
*/

#include <stdio.h>
#include "WHERE_FILES:sh_test.h"

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL
        INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON SALES_PEOPLE.EMPNO             EmpNo;
BASED_ON SALES_PEOPLE.LAST_NAME         Last_Name;
BASED_ON SALES_PEOPLE.FIRST_NAME        First_Name;


char Test[]="SELECT T1.EMPNO,T1.LAST_NAME, T1.FIRST_NAME \
FROM SALES_PEOPLE T1 WHERE SINGULAR \
(SELECT * FROM SALES T2 WHERE T1.EMPNO=T2.SALES_REP \
AND T2.TOTAL_VALUE > 6000 AND EXISTS \
(SELECT * FROM CUSTOMERS T3)) AND SINGULAR \
(SELECT * FROM SALES_PERF T4 WHERE T4.EMPNO = T1.EMPNO)";

void Underline();

main(argc, argv)
int argc;
char *argv[];
{
	
	int verbose, Count;
	Count = 0;

	/*--- check if verbose is requested ------ */
	verbose = FALSE;
	if (--argc > 0){	
		if (*argv[1] == 'v' || *argv[1] == 'V')
			verbose = TRUE;
	}
        printf("Test:\n %s\n",Test);
        Underline(80);
        EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT T1.EMPNO,T1.LAST_NAME, T1.FIRST_NAME
                FROM SALES_PEOPLE T1 WHERE SINGULAR
                (SELECT * FROM SALES T2 WHERE T1.EMPNO=T2.SALES_REP
                AND T2.TOTAL_VALUE > 6000 AND EXISTS
                (SELECT * FROM CUSTOMERS T3)) 
		AND SINGULAR (SELECT * FROM SALES_PERF T4 
                WHERE T4.EMPNO = T1.EMPNO);

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :EmpNo, :Last_Name, :First_Name;


        while (SQLCODE == 0){
		Count++;

                printf("%d\t",EmpNo);
                printf("%s\t",Last_Name);
                printf("%s\n",First_Name);
                Underline(80);
		
                EXEC SQL
                        FETCH CR INTO :EmpNo, :Last_Name, :First_Name;

        }
	
NOMORE:
	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}



/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e sin007.e
$ CC FLAG_CC sin007.c
$ LINK FLAG_LINK sin007 
$ RUN sin007
$ CREATE sin007.qli
ready WHERE_GDB:sh_test.gdb;
set semicolon;

select t1.empno,t1.last_name, t1.first_name
from sales_people t1 where singular 
(select * from sales t2 where t1.empno=t2.sales_rep 
and t2.total_value > 6000 and exists
(select * from customers t3)) and singular
(select * from sales_perf t4 where t4.empno = t1.empno);

for t1 in sales_people with unique t2 in sales with t1.empno=t2.sales_rep
and t2.total_value > 6000
for t4 in sales_perf with t4.empno = t1.empno
print t1.empno, t1.last_name, t1.first_name;

select t1.empno,t1.last_name, t1.first_name
from sales_people t1 where 1 =
(select count(*) from sales t2 where t1.empno=t2.sales_rep
and t2.total_value > 6000 and exists
(select * from customers t3)) and 1 =
(select count(*) from sales_perf t4 where t4.empno = t1.empno);
finish;
quit;
$ QLI -n -a sin007.qli
$ CREATE sin007.sql
connect WHERE_GDB:sh_test.gdb;
select t1.empno,t1.last_name, t1.first_name
from sales_people t1 where singular 
(select * from sales t2 where t1.empno=t2.sales_rep 
and t2.total_value > 6000 and exists
(select * from customers t3)) and singular
(select * from sales_perf t4 where t4.empno = t1.empno);
select t1.empno,t1.last_name, t1.first_name
from sales_people t1 where 1 =
(select count(*) from sales t2 where t1.empno=t2.sales_rep
and t2.total_value > 6000 and exists
(select * from customers t3)) and 1 =
(select count(*) from sales_perf t4 where t4.empno = t1.empno);
quit;
$ISQL -m -i sin007.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE sin007* 

