
#
#**********************************************************************
# Purpose:		Test predicates support in InterBase SQL 4.0
# Syntax:		[NOT]SINGULAR <subquery>			
# Description:           Two table joins in outer-query
#
#                         SELECT T1.EMPNO,T1.LAST_NAME, T1.FIRST_NAME,
#                         T2.JOB, T2.SALARY, T2.HIRE_DATE
#                         FROM SALES_PEOPLE T1 , EMPLOYEES T2
#                         WHERE T1.EMPNO = T2.EMPNO AND SINGULAR
#                         (SELECT *
#                         FROM SALES T3
#                         WHERE T3.SALES_REP = T2.EMPNO
#                         AND T3.TOTAL_VALUE > 6000);
#
# Tables:                sales_people, employees, sales
# Author:                Sam Hakim, Feb 19, 1993
# ***********************************************************************
#

$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
>> sin008.e

#include <stdio.h>
#include <time.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON SALES_PEOPLE.EMPNO             EmpNo;
BASED_ON SALES_PEOPLE.LAST_NAME         Last_Name;
BASED_ON SALES_PEOPLE.FIRST_NAME        First_Name;
BASED_ON EMPLOYEES.JOB                  Job;
BASED_ON EMPLOYEES.SALARY               Salary;
BASED_ON EMPLOYEES.HIRE_DATE            Hire_Date;

static char             *months [] ={
                    "Jan",
                    "Feb",
                    "Mar",
                    "Apr",
                    "May",
                    "Jun",
                    "Jul",
                    "Aug",
                    "Sep",
                    "Oct",
                    "Nov",
                    "Dec"
};

void ToDate();
char AlphaDate[13];                     
struct tm UxTime;




char Test[]="SELECT T1.EMPNO,T1.LAST_NAME, T1.FIRST_NAME, \
T2.JOB, T2.SALARY, T2.HIRE_DATE \
FROM SALES_PEOPLE T1 , EMPLOYEES T2 \
WHERE T1.EMPNO = T2.EMPNO AND SINGULAR \
(SELECT * \
FROM SALES T3 \
WHERE T3.SALES_REP = T2.EMPNO \
AND T3.TOTAL_VALUE > 6000)";

void Underline();

main(argc, argv)
int argc;
char *argv[];

{
	int Count = 0;
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                 SELECT T1.EMPNO,T1.LAST_NAME, T1.FIRST_NAME,
                 T2.JOB, T2.SALARY, T2.HIRE_DATE
                 FROM SALES_PEOPLE T1 , EMPLOYEES T2
                 WHERE T1.EMPNO = T2.EMPNO AND SINGULAR
                 (SELECT *
                 FROM SALES T3
                 WHERE T3.SALES_REP = T2.EMPNO
                 AND T3.TOTAL_VALUE > 6000);


        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :EmpNo,:Last_Name,:First_Name,:Job,:Salary,:Hire_Date

        while (SQLCODE == 0){
		Count++;

                printf("%d\t",EmpNo);
                printf("%s\t",Last_Name);
                printf("%s\t",First_Name);
                printf("%s\t",Job);
                printf("%8.2f\t", (double)(Salary/100));
                ToDate(&Hire_Date);
                printf("%s\n",AlphaDate);
                Underline(80);

		
                EXEC SQL
                FETCH CR INTO :EmpNo,:Last_Name,:First_Name,:Job,:Salary,:Hire_Date

        }
	
NOMORE:
	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}

/****************************************************************
 * Convert Interbase date to character string date
 ****************************************************************
*/
void ToDate(InDate)
GDS__QUAD *InDate;
{
                isc_decode_date (InDate, &UxTime);
                sprintf (AlphaDate, "%2d-%s-%4d ", UxTime.tm_mday,
	 	months[UxTime.tm_mon], UxTime.tm_year + 1900);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e sin008.e
$ CC FLAG_CC sin008.c
$ LINK FLAG_LINK sin008 
$ RUN sin008
>> sin008.sql
connect WHERE_GDB:sh_test.gdb;
select t1.empno,t1.last_name, t1.first_name,t2.job, t2.salary, t2.hire_date 
from sales_people t1 , employees t2 where t1.empno = t2.empno and singular 
(select * from sales t3 where t3.sales_rep = t2.empno 
and t3.total_value > 6000);
select t1.empno,t1.last_name, t1.first_name,t2.job, t2.salary, t2.hire_date 
from sales_people t1 , employees t2 where t1.empno = t2.empno and 1 =
(select count(*) from sales t3 where t3.sales_rep = t2.empno
and t3.total_value > 6000);
quit;
$ISQL -m -i sin008.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE sin008* 

