
#
#HISTORY:
#2001-May-20 Neil McCalden  
#Use explicit order by clause as generic sort order is not consistent across
#different systems (little vs big endian).
#2001-Aug-27 Neil McCalden - fix sort order to match output data and join_3
#

$ GBAK -r WHERE_FILES:atlas.gbak WHERE_GDB:atlas_join_4.gdb
>> join004.e

/*
 Out join example 2.9.1 page 64 - 4
 
*/


DATABASE atlas = FILENAME "WHERE_GDB:atlas_join_4.gdb";
#include <stdio.h>

BASED_ON BASEBALL_TEAMS.TEAM_NAME	Team_Name;
BASED_ON CITIES.CITY			City;
BASED_ON STATES.STATE_NAME		State_Name;

short StateFlag;


EXEC SQL
	INCLUDE SQLCA;

main()
{

EXEC SQL
	DECLARE C CURSOR FOR
	SELECT B.TEAM_NAME, C.CITY, S.STATE_NAME  
	FROM (CITIES C LEFT JOIN STATES S ON S.STATE = C.STATE)
	,BASEBALL_TEAMS B WHERE B.CITY = C.CITY
	ORDER BY B.TEAM_NAME, C.CITY, S.STATE_NAME;
	
EXEC SQL
	OPEN C;


printf("Team Name \t\t City \t\t State\n");
printf("--------- \t\t ---- \t\t ------\n");

do{
	EXEC SQL FETCH C INTO :Team_Name,:City, :State_Name:StateFlag;
	if (!SQLCODE){
		if (StateFlag)
			strcpy(State_Name,"- NULL -");
		printf ("%-20s ",Team_Name);
		printf ("%-20s ",City);
		printf (" %-20s\n", State_Name);
	}
}while (SQLCODE == 0);

EXEC SQL CLOSE C;

printf("... End of example 2.9.1 \n");
}
$ GPRE -e join004.e
$ CC FLAG_CC join004.c
$ LINK FLAG_LINK join004 
$ RUN join004
>> join004.sql
connect WHERE_GDB:atlas_join_4.gdb;
SELECT B.TEAM_NAME, C.CITY, S.STATE_NAME
FROM (CITIES C LEFT JOIN STATES S ON S.STATE = C.STATE)
,BASEBALL_TEAMS B WHERE B.CITY = C.CITY
ORDER BY B.TEAM_NAME, C.CITY, S.STATE_NAME;
quit;
$ISQL -m -i join004.sql
$DROP WHERE_GDB:atlas_join_4.gdb
$ DELETE join004*
