
$ GBAK -rep sh_blobs.gbk WHERE_GDB:sh_blobs_18.gdb
>> blob018.epp
/**********************************************************************
 Purpose:               Test SQL blob support in InterBase 4.0
 Description:           INSERT CURSOR - Use a local pointer to store the blob. 
 Author:                Sam Hakim, June 7, 93
 **********************************************************************/
#include <stdio.h>
#include <cstdlib>
#include <cstring>

using namespace std;

DATABASE DB = "WHERE_GDB:sh_blobs_18.gdb";
EXEC SQL	INCLUDE SQLCA;
EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;

BASED_ON MB1.TEST_NAME      Test_Name;
BASED_ON MB1.COMMENT        Comment;
BASED_ON MB1.ROW_ID         Row_Id;
BASED_ON MB1.B512           BlobId;

bool verbose;

struct Buf{
    char            *Buffer;
    unsigned short  BufferLen;
};
struct Buf M;

char Test[]="INSERT CURSOR BCW VALUES (:M.Buffer:M.BufferLen), M.Buffer is a pointer";

void Underline(int);
void CreateLine(char *Bf,int L);
void EmptyBuffer(char *Bf,int L);

int main(int argc, char* argv[])
{
short                       i,j,k,l;
int Count;

    verbose = false;
    if (--argc > 0){
        if (*argv[1] == 'v' || *argv[1] == 'V')
            verbose = true;
        }

       
    Count = 0;
    strcpy(Test_Name,"blob018");
    printf ("Test:\n %s\n",Test);
    Underline(80);

    M.BufferLen = 512;
    M.Buffer = (char*) malloc(M.BufferLen);

    EXEC SQL DECLARE BCW CURSOR FOR INSERT BLOB B512 INTO MB1;

    for (j = 18; j < 19; j++){
        EXEC SQL OPEN BCW INTO :BlobId;      	/* This will change in G to INTO */

        for (i=1; i<5; i++){
            sprintf (M.Buffer,"Line: %d>",i);
            CreateLine(M.Buffer,M.BufferLen);
            EXEC SQL
                INSERT CURSOR BCW VALUES (:M.Buffer:M.BufferLen);
	   	  if (verbose)
		      printf("SQLCODE %d, BufferLen %d \n",SQLCODE,M.BufferLen);
            EmptyBuffer(M.Buffer,M.BufferLen);
        }
	EmptyBuffer(M.Buffer,M.BufferLen);
	sprintf (M.Buffer,"Line: %d> --- End of BLOB B512 ---",i);
	EXEC SQL
                INSERT CURSOR BCW VALUES (:M.Buffer:M.BufferLen);
    EXEC SQL
        CLOSE BCW;
    EXEC SQL
        INSERT INTO MB1 (TEST_NAME,ROW_ID,B512) VALUES (:Test_Name,:j,:BlobId);
    EXEC SQL COMMIT;
    }

FINISH;

exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds_status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/************************************************************
 * Draw and underline
 ************************************************************/
void Underline(int i)
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}
/***********************************************************
 * EmptyBuffer
 * print an underline
 ***********************************************************/
void EmptyBuffer(char *Bf,int L)
{
char *s;
for (s=Bf;L;L--)
	*s++ = ' ';
}
/************************************************************
 * Create a new line for the blob content.
 ************************************************************/
void CreateLine(char *Bf,int L)
{
char      TempBuf[5],*s;
int	  i,j,t,k;

     
     t = sizeof(TempBuf);
     j = 0;

     for (i = 9; i < L-5; ){
	j++;
	sprintf (TempBuf,"%3d,",j);
	strncat(Bf,TempBuf,t); 
	i += t-1;	/* Ignore the terminating null */
     }
	strncat(Bf,"<EOL",5);
if (verbose)
	printf("%s\n",Bf);
}


$ GPRE -e blob018.epp
$ CXX FLAG_CXX blob018.cpp
$ LINK FLAG_LINK blob018 
$ RUN blob018
>> blob018.qli
ready WHERE_GDB:sh_blobs_18.gdb;
select test_name, row_id, b512 from mb1 where test_name = 'blob018'; 
finish;
quit;
$ QLI -n -a blob018.qli
$DROP WHERE_GDB:sh_blobs_18.gdb
$ DELETE blob018* 
