
$ GBAK -rep sh_blobs.gbk WHERE_GDB:sh_blobs_29.gdb
>> blob090.epp
/**********************************************************************
 Purpose:               Test SQL blob support in InterBase 4.0
 Description:           INSERT CURSOR - No <length> specified 
 Expected result:	Illegal syntax - segment length is required
 Author:                Sam Hakim, June 7, 93
 **********************************************************************/
#include <stdio.h>
#include <cstdlib>
#include <cstring>

DATABASE DB = "WHERE_GDB:sh_blobs_29.gdb";
EXEC SQL	INCLUDE SQLCA;
EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;

BASED_ON MB1.COMMENT        Comment;
BASED_ON MB1.ROW_ID         Row_Id;
BASED_ON MB1.B256           BlobId;
BASED_ON MB1.TEST_NAME      Test_Name;

char                        TempBuf[4];
short                       i,j,k,l;

struct Buf{
    char            Buffer[256];
	unsigned short	BufferLen;
};
struct Buf M;

char Test[]="INSERT CURSOR BCW VALUES (:M.Buffer)";

void Underline(int);
void CreateLine(char Bf[]);
void Append(char s[], char t[]);

int main(int argc, char* argv[])
{
    int Count;
    bool verbose;

    verbose = false;
    if (--argc > 0){
        if (*argv[1] == 'v' || *argv[1] == 'V')
            verbose = true;
        }

    READY;              /* Bug 4549 will be fixed in verion G */
   
    Count = 0;

    printf ("Test:\n %s\n",Test);
    Underline(80);
    strcpy(Test_Name,"blob005");

    EXEC SQL
    DECLARE BCW CURSOR FOR
    INSERT BLOB B256 INTO MB1 MAXIMUM_SEGMENT 256;

    for (j = 8; j < 10; j++){
        EXEC SQL
        OPEN BCW INTO :BlobId;      /* This will change in G to INTO */

        for (i=1; i<100; i++){

            sprintf (M.Buffer,"Line: %2d ",i);
            CreateLine(M.Buffer);
            M.BufferLen = strlen(M.Buffer);
            EXEC SQL
                INSERT CURSOR BCW VALUES (:M.Buffer);
        }
    EXEC SQL
        CLOSE BCW;
    EXEC SQL
        INSERT INTO MB1 (TEST_NAME,ROW_ID,B256) VALUES (:Test_Name,:j,:BlobId);
    EXEC SQL COMMIT;
    }

FINISH;

exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds_status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/************************************************************
 * Draw an underline
 ************************************************************/
void Underline(int i)
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}
/************************************************************
 * Append t to s
 ************************************************************/
void Append(char s[], char t[])
{
    int i,j;
    i = j = 0;
    while (s[i] != '\0')
        i++;
    while ((s[i++] = t[j++]) != '\0')   /* copy t */
        ;
}
/************************************************************
 * Create a new line for the blob content.
 ************************************************************/
void CreateLine(char Bf[])
{
char            TempBuf[4];
short		i;
     TempBuf[3]=0;

     for (i = 1; i < 21; i++){
	sprintf (TempBuf,"%2d,",i);
        Append(Bf,TempBuf);
	}
}

$ GPRE -e blob090.epp
$DROP WHERE_GDB:sh_blobs_29.gdb
$ DELETE blob090*
