
#/**********************************************************************
# Purpose:		Test predicates support in InterBase SQL 4.0
# 
# Syntax:                <column-spec> [NOT] CONTAINING <value-spec>
#
# Description:           blob-field containing a single char
#
#                        SELECT PROJ_NO
#                        FROM PROJECTS
#                        WHERE PROJ_DESC CONTAINING 'A';
#
#
# Tables:                projects
#
# Author:                Sam Hakim, Feb 19, 93
#
# Note:                  GDML will be used to print blobs as SQL blob support
#                        was not available at this time this test was written.
# ***********************************************************************

$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
>> con020.e

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON PROJECTS.PROJ_NO       Proj_No;


char Test[]="SELECT PROJ_NO \
FROM PROJECTS \
WHERE PROJ_DESC CONTAINING 'A'";

void Underline();

main(argc, argv)
int argc;
char *argv[];

{
	int Count = 0;
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT PROJ_NO
                FROM PROJECTS
                WHERE PROJ_DESC CONTAINING 'A';

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :Proj_No;

        while (SQLCODE == 0){

                Count++;
                printf("%s\n",Proj_No);
                Underline(80);

                EXEC SQL
                FETCH CR INTO :Proj_No;
        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);


        printf("\n* Using GDML to print blob \n");

        for p in projects with p.proj_desc containing 'A'
                printf("%s\n",p.proj_no);
                for pb in p.proj_desc
                        pb.segment[pb.length] = '\0';
                        printf ("%s", pb.segment);
                end_for;
                printf ("\n");
        end_for;


	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}


/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e con020.e
$ CC FLAG_CC con020.c
$ LINK FLAG_LINK con020 
$ RUN con020
>> con020.qli
set semicolon;
ready WHERE_GDB:sh_test.gdb;
SELECT PROJ_NO
FROM PROJECTS
WHERE PROJ_DESC CONTAINING 'A';

FOR P IN PROJECTS WITH P.PROJ_DESC CONTAINING 'A' PRINT P.PROJ_NO;
FINISH;
QUIT;

$ QLI -n -a con020.qli
>> con020.sql
connect WHERE_GDB:sh_test.gdb;
SELECT PROJ_NO
FROM PROJECTS
WHERE PROJ_DESC CONTAINING 'A';
quit;
$ISQL -m -i con020.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE con020* 
