
$ GBAK -r WHERE_FILES:sh_join.gbk WHERE_GDB:sh_join_26.gdb
$ CREATE join026.e

/**********************************************************************
 Purpose:               Test SQL OUTER JOIN support in InterBase 4.0
 Description:           DISTINCT LEFT JOIN
 Author:                Sam Hakim, June 1, 93
 ***********************************************************************
*/

#include <stdio.h>

DATABASE DB = "WHERE_GDB:sh_join_26.gdb";
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON st1.s1     t1s1;
BASED_ON st1.s2     t1s2;
BASED_ON st1.table_row   t1table_row;
BASED_ON st2.s1	    t2s1;
BASED_ON st2.s2     t2s2;
BASED_ON st2.table_row   t2table_row;

char Test[]="\
select distinct x.s1,x.s2,y.s1,y.s2 \
from (st5 x left join st1 y on x.s2 = y.s2)";

void Underline();

main()
{
	
    int Count;
	Count = 0;
    printf ("Test:\n %s\n",Test);
    Underline(80);

    EXEC SQL
                DECLARE CR CURSOR FOR
                select distinct x.s1,x.s2,y.s1,y.s2
                from (st5 x left join st1 y on x.s2 = y.s2);

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :t1s1,:t1s2,:t2s1,:t2s2;

        while (SQLCODE == 0){
		Count++;

                printf("%5d  ",t1s1);
                printf("%5d  ",t1s2);
		printf("%5d  ",t2s1);
                printf("%5d\n",t2s2);

                EXEC SQL
                FETCH CR INTO :t1s1,:t1s2,:t2s1,:t2s2;
        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;

exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e join026.e
$ CC FLAG_CC join026.c
$ LINK FLAG_LINK join026 
$ RUN join026
$ CREATE join026.qli
ready WHERE_GDB:sh_join_26.gdb;
set semicolon;
set columns 100;

select distinct x.s1,x.s2,y.s1,y.s2
from (st5 x left join st1 y on x.s2 = y.s2);

finish;
quit;
$ QLI -n -a join026.qli
$ CREATE join026.sql
connect WHERE_GDB:sh_join_26.gdb;
select distinct x.s1,x.s2,y.s1,y.s2
from (st5 x left join st1 y on x.s2 = y.s2);
quit;
$ISQL -m -i join026.sql
$DROP WHERE_GDB:sh_join_26.gdb
$ DELETE join026* 
