
#/**********************************************************************
# Purpose:		Test predicates support in InterBase SQL 4.0
#
# Syntax:                <column-spec> [NOT] CONTAINING <value-spec>
#
# Description:           char-field, containing mixture of lower and
#                        upper case char
#
#                        SELECT CUSTNO, CUSTOMER FROM CUSTOMERS
#                        WHERE CUSTOMER CONTAINING 'A'
#                        OR CUSTOMER CONTAINING 'c' ORDER BY CUSTNO;
#
# Tables:                customers
#
# Author:                Sam Hakim, Feb 19, 93
# ***********************************************************************

$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
>> con005.e

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON CUSTOMERS.CUSTNO               CustNo;
BASED_ON CUSTOMERS.CUSTOMER             Customer;
char Test[]="SELECT CUSTNO, CUSTOMER FROM CUSTOMERS \
WHERE CUSTOMER CONTAINING 'A' \
OR CUSTOMER CONTAINING 'c' ORDER BY CUSTNO";

void Underline();

int main(argc, argv)
int argc;
char *argv[];

{
	int Count = 0;
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT CUSTNO, CUSTOMER FROM CUSTOMERS
                WHERE CUSTOMER CONTAINING 'A'
                OR CUSTOMER CONTAINING 'c' ORDER BY CUSTNO;

        EXEC SQL
		OPEN CR;

	EXEC SQL
                FETCH CR INTO :CustNo, :Customer;


        while (SQLCODE == 0){
		Count++;

                printf("%d\t",CustNo);
                printf("%s\n",Customer);
                Underline(80);

                EXEC SQL
                FETCH CR INTO :CustNo, :Customer;

        }

NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


return 0;

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	return 1;
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e con005.e
$ CC FLAG_CC con005.c
$ LINK FLAG_LINK con005
$ RUN con005
>> con005.sql
connect WHERE_GDB:sh_test.gdb;
select count(*) from customers
where customer containing 'A' or customer containing 'c';
quit;
$ISQL -m -i con005.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE con005*

