
$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
$ CREATE con003.e
/**********************************************************************
 Purpose:		Test predicates support in InterBase SQL 4.0
 
 Syntax:                <column-spec> [NOT] CONTAINING <value-spec>

 Description:           char-field, containing a single upper char

                        SELECT CUSTNO, CUSTOMER
                        FROM CUSTOMERS
                        WHERE CUSTOMER CONTAINING 'A'
                        ORDER BY CUSTNO;

 Tables:                customers

 Expected result:	 

 Author:                Sam Hakim, Feb 19, 93
 ***********************************************************************
*/

#include <stdio.h>
#include "WHERE_FILES:sh_test.h"

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON CUSTOMERS.CUSTNO               CustNo;
BASED_ON CUSTOMERS.CUSTOMER             Customer;

char Test[]="SELECT CUSTNO, CUSTOMER \
FROM CUSTOMERS \
WHERE CUSTOMER CONTAINING 'A' \
ORDER BY CUSTNO";

void Underline();



main(argc, argv)
int argc;
char *argv[];

{
	
	int verbose, Count;
	Count = 0;

	/*--- check if verbose is requested ------ */
	verbose = FALSE;
	if (--argc > 0){	
		if (*argv[1] == 'v' || *argv[1] == 'V')
			verbose = TRUE;
	}
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT CUSTNO, CUSTOMER
                FROM CUSTOMERS
                WHERE CUSTOMER CONTAINING 'A'
                ORDER BY CUSTNO;

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :CustNo, :Customer;


        while (SQLCODE == 0){
		Count++;

                printf("%d\t",CustNo);
                printf("%s\n",Customer);
                Underline(80);

                EXEC SQL
                FETCH CR INTO :CustNo, :Customer;

        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}

/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e con003.e
$ CC FLAG_CC con003.c
$ LINK FLAG_LINK con003 
$ RUN con003
$ CREATE con003.qli
set semicolon;
ready WHERE_GDB:sh_test.gdb;
SELECT CUSTNO, CUSTOMER
FROM CUSTOMERS
WHERE CUSTOMER CONTAINING 'A'
ORDER BY CUSTNO;

FOR C IN CUSTOMERS SORTED BY C.CUSTNO WITH C.CUSTOMER CONTAINING 'A'
PRINT C.CUSTNO, C.CUSTOMER;
FINISH;
QUIT;
$ QLI -n -a con003.qli
$ CREATE con003.sql
connect WHERE_GDB:sh_test.gdb;
SELECT CUSTNO, CUSTOMER
FROM CUSTOMERS
WHERE CUSTOMER CONTAINING 'A'
ORDER BY CUSTNO;
quit;
$ISQL -i con003.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE con003* 

