
#/**********************************************************************
# Purpose:		Test predicates support in InterBase SQL 4.0
#			[NOT]SINGULAR <subquery>			
#
# Description:           SINGULAR - subquery uses CONTAINING
#
#                        SELECT * FROM CUSTOMERS C1 WHERE SINGULAR
#                        (SELECT * FROM SALES S1
#                        WHERE S1.CUSTNO = C1.CUSTNO
#                        AND S1.PONUMB CONTAINING '8902')
#
# Tables:		customers		
#
# Author:		Sam Hakim, Feb 18, 93
#************************************************************************

$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
>> sin027.e

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL	WHENEVER SQLERROR GO TO ERR_LBL;

BASED_ON CUSTOMERS.CUSTNO	CustNo;
BASED_ON CUSTOMERS.CUSTOMER	Customer;
BASED_ON CUSTOMERS.CONTACT	Contact;
BASED_ON CUSTOMERS.ADDRESS	Address;
BASED_ON CUSTOMERS.CITY		City;
BASED_ON CUSTOMERS.STATE	State;
BASED_ON CUSTOMERS.ZIP_CODE	Zip_Code;
BASED_ON CUSTOMERS.PHONE_NO	Phone_No;
BASED_ON CUSTOMERS.ON_HOLD	On_Hold;

void Underline();
void pad();


char Test[]="SELECT * FROM CUSTOMERS C1 WHERE SINGULAR \
(SELECT * FROM SALES S1 \
WHERE S1.CUSTNO = C1.CUSTNO \
AND S1.PONUMB CONTAINING '8902')";

void Underline();
main(argc, argv)
int argc;
char *argv[];
{
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
		DECLARE CR CURSOR FOR 
                SELECT * FROM CUSTOMERS C1 WHERE SINGULAR
                (SELECT * FROM SALES S1
                WHERE S1.CUSTNO = C1.CUSTNO
                AND S1.PONUMB CONTAINING '8902')
		 
		 
	EXEC SQL
		OPEN CR;
		
	EXEC SQL
		FETCH CR INTO :CustNo, :Customer, :Contact, :Address, :City, 
		:State, :Zip_Code, :Phone_No, :On_Hold;
		
	while (SQLCODE == 0){
                pad(Customer,sizeof(Customer));
                pad(Contact,sizeof(Contact));
                pad(Address,sizeof(Address));
                pad(City,sizeof(City));
                pad(State,sizeof(State));
                pad(Zip_Code,sizeof(Zip_Code));
                pad(Phone_No,sizeof(Phone_No));

		printf ("%ld\t",CustNo);
		printf ("%s\t",Customer);
                printf ("%s\t",Contact);
                printf ("%s\n",Address);
		printf ("%s\t",City);
		printf ("%s\t",State);
                printf ("%s\t",Zip_Code);
		printf ("%s\t",Phone_No);
		printf ("%s\n",On_Hold);
                Underline(90);
		
	EXEC SQL
		FETCH CR INTO :CustNo, :Customer, :Contact, :Address, :City, 
		:State, :Zip_Code, :Phone_No, :On_Hold;	
	}
	
	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

/***************************************************************
 * pad the character string with blanks
 ***************************************************************
*/
void pad(string,l)
char *string;
int l;
{

char *s;
int i;

i = 1;
s = string;

while (*s){
	s++;
	i++;
}
for (;i<l;s++,i++)
	*s=' ';	
*s='\0';
}

$ GPRE -e sin027.e
$ CC FLAG_CC sin027.c
$ LINK FLAG_LINK sin027 
$ RUN sin027
>> sin027.sql
connect WHERE_GDB:sh_test.gdb;
select * from customers c1 where singular 
(select * from sales s1 
where s1.custno = c1.custno and s1.ponumb containing '8902');

select * from customers c1 where 1 =
(select count(*) from sales s1
where s1.custno = c1.custno and s1.ponumb containing '8902');
quit;
$ISQL -m -i sin027.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE sin027* 

