
$ GBAK -r WHERE_FILES:sh_join.gbk WHERE_GDB:sh_join_17.gdb
$ CREATE join017.e

/**********************************************************************
 Purpose:               Test SQL OUTER JOIN support in InterBase 4.0
 Description:           WHERE, LIKE, ORDER BY - 3 table outer joins
 Author:                Sam Hakim, June 1, 93
 ***********************************************************************
*/

#include <stdio.h>
#include "WHERE_FILES:sh_test.h"

DATABASE DB = "WHERE_GDB:sh_join_17.gdb";
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON ct1.c1      t1c1;
BASED_ON ct1.c10     t1c10;
BASED_ON ct1.table_row   t1table_row;

BASED_ON ct2.c1      t2c1;
BASED_ON ct2.c10     t2c10;
BASED_ON ct2.table_row   t2table_row;

BASED_ON ct3.c1      t3c1;
BASED_ON ct3.c10     t3c10;
BASED_ON ct3.table_row   t3table_row;

char Test[]="\
select x.c1,x.c10,x.table_row,y.c1,y.c10,y.table_row,z.c1,z.c10,z.table_row \
from (ct1 x left join ct2 y on x.c1 = y.c1) right join ct5 z on z.c1 = x.c1 \
where x.c1 like 'a%' \
order by x.c1 ascending";

void Underline();

main()
{
	
    int Count;
	Count = 0;
    printf ("Test:\n %s\n",Test);
    Underline(80);

    EXEC SQL
                DECLARE CR CURSOR FOR
                select x.c1,x.c10,x.table_row,y.c1,y.c10,y.table_row,z.c1,z.c10,z.table_row
                from (ct1 x left join ct2 y on x.c1 = y.c1) right join ct5 z on z.c1 = x.c1
                where x.c1 like 'a%'
                order by x.c1 ascending;

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :t1c1,:t1c10,:t1table_row,
                :t2c1,:t2c10,:t2table_row,
                :t3c1,:t3c10,:t3table_row;

        while (SQLCODE == 0){
		Count++;

                printf("%-10s  ",t1c1);
                printf("%-10s  ",t1c10);
                printf("%-10s  ",t1table_row);
		
                printf("%-10s  ",t2c1);
                printf("%-10s  ",t2c10);
                printf("%-10s  ",t2table_row);

                printf("%-10s  ",t3c1);
                printf("%-10s  ",t3c10);
                printf("%-10s\n",t3table_row);

                EXEC SQL
                FETCH CR INTO :t1c1,:t1c10,:t1table_row, 
                :t2c1,:t2c10,:t2table_row, 
                :t3c1,:t3c10,:t3table_row;


        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e join017.e
$ CC FLAG_CC join017.c
$ LINK FLAG_LINK join017 
$ RUN join017
$ CREATE join017.qli
ready WHERE_GDB:sh_join_17.gdb;
set semicolon;
set columns 100;

select x.c1,x.c10,x.table_row,y.c1,y.c10,y.table_row,z.c1,z.c10,z.table_row
from (ct1 x left join ct2 y on x.c1 = y.c1) right join ct5 z on z.c1 = x.c1
where x.c1 like 'a%'
order by x.c1 ascending;
finish;
quit;
$ QLI -n -a join017.qli
$ CREATE join017.sql
connect WHERE_GDB:sh_join_17.gdb;
select x.c1,x.c10,x.table_row,y.c1,y.c10,y.table_row,z.c1,z.c10,z.table_row
from (ct1 x left join ct2 y on x.c1 = y.c1) right join ct5 z on z.c1 = x.c1
where x.c1 like 'a%'
order by x.c1 ascending;
quit;
$ISQL -m -i join017.sql
$DROP WHERE_GDB:sh_join_17.gdb
$ DELETE join017* 
