
$ GBAK -r WHERE_FILES:sh_join.gbk WHERE_GDB:sh_join_16.gdb
$ CREATE join016.e

/**********************************************************************
 Purpose:               Test SQL OUTER JOIN support in InterBase 4.0
 Description:           HAVING clause of joined table
 Author:                Sam Hakim, June 1, 93
 ***********************************************************************
*/

#include <stdio.h>

DATABASE DB = "WHERE_GDB:sh_join_16.gdb";
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON st1.s1     t1s1;
BASED_ON st1.s1     sums1;

char Test[]="\
qli core dumps with this one - fixe will appear in G \n \
select sum(y.s1), y.s1 \
from (st1 x left join st5 y on x.s1 = y.s1) \
group by y.s1 \
having sum(y.s1) > 1 \
order by y.s1 ascending";

void Underline();

main()
{
	
    int Count;
	Count = 0;
    printf ("Test:\n %s\n",Test);
    Underline(80);

    EXEC SQL
                DECLARE CR CURSOR FOR
                select sum(y.s1), y.s1
                from (st1 x left join st5 y on x.s1 = y.s1)
                group by y.s1
                having sum(y.s1) > 1
                order by y.s1 ascending;

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :sums1,:t1s1;


        while (SQLCODE == 0){
		Count++;

                printf("%d     ",sums1);
                printf("%d\n",t1s1);
		
                EXEC SQL
                FETCH CR INTO :sums1,:t1s1;

        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e join016.e
$ CC FLAG_CC join016.c
$ LINK FLAG_LINK join016 
$ RUN join016
$ CREATE join016.qli
ready WHERE_GDB:sh_join_16.gdb;
set semicolon;
set columns 100;

/* qli core dumps with this one - fixe will appear in G */
select sum(y.s1), y.s1
from (st1 x left join st5 y on x.s1 = y.s1) 
group by y.s1
having sum(y.s1) > 1
order by y.s1 ascending;
finish;
quit;
$ QLI -n -a join016.qli
$ CREATE join016.sql
connect WHERE_GDB:sh_join_16.gdb;
select sum(y.s1), y.s1
from (st1 x left join st5 y on x.s1 = y.s1) 
group by y.s1
having sum(y.s1) > 1
order by y.s1 ascending;
quit;
$ISQL -m -i join016.sql
$DROP WHERE_GDB:sh_join_16.gdb
$ DELETE join016* 
