
#
#**********************************************************************
# Purpose:		Test predicates support in InterBase SQL 4.0
# 
# Syntax:
#
# Description:           field starting with another field
#
#                        SELECT NAME
#                        FROM EMPLOYEES
#                        WHERE NAME STARTING WITH FIRST_NAME
#                        ORDER BY NAME;
#
# Table:                 employees
#
# Author:                Sam Hakim, Feb 19, 93
# ***********************************************************************
#

$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
>> sta037.e

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;

EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON EMPLOYEES.NAME         Name;



char Test[]="SELECT NAME \
FROM EMPLOYEES \
WHERE NAME STARTING WITH FIRST_NAME \
ORDER BY NAME";

void Underline();

main(argc, argv)
int argc;
char *argv[];

{
	int Count = 0;
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                        SELECT NAME
                        FROM EMPLOYEES
                        WHERE NAME STARTING WITH FIRST_NAME
                        ORDER BY NAME;

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :Name;

        while (SQLCODE == 0){

                Count++;
                printf("%s\n",Name);
                Underline(80);

                EXEC SQL
                        FETCH CR INTO :Name;
        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}
$ GPRE -e sta037.e
$ CC FLAG_CC sta037.c
$ LINK FLAG_LINK sta037 
$ RUN sta037
>> sta037.qli

ready WHERE_GDB:sh_test.gdb;
set semicolon;
SELECT NAME FROM EMPLOYEES 
WHERE NAME STARTING WITH FIRST_NAME ORDER BY NAME;
for employees sorted by name with name starting with first_name
print name;
select count(*) from employees where name starting with
first_name;
finish;
quit;
$ QLI -n -a sta037.qli
>> sta037.sql
connect WHERE_GDB:sh_test.gdb;
SELECT NAME FROM EMPLOYEES 
WHERE NAME STARTING WITH FIRST_NAME ORDER BY NAME;
select count(*) from employees where name starting with
first_name;
quit;
$ISQL -m -i sta037.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE sta037* 

