
#/**********************************************************************
# Purpose:		Test predicates support in InterBase SQL 4.0
# 
# Syntax:                <column-spec> [NOT] CONTAINING <value-spec>
#
# Description:           varchar field containing a single char
#                        SELECT JOB
#                        FROM EMPLOYEES
#                        WHERE JOB CONTAINING 'M'
#                        ORDER BY JOB;
#
# Tables:                Employees
#
# Author:                Sam Hakim, Feb 19, 93
# ***********************************************************************


$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
>> con027.e

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON EMPLOYEES.JOB          Job;


char Test[]="SELECT JOB \
FROM EMPLOYEES \
WHERE JOB CONTAINING 'M' \
ORDER BY JOB";

void Underline();

main(argc, argv)
int argc;
char *argv[];

{
	int Count = 0;
        printf("Test:\n %s\n",Test);
        Underline(80);
	EXEC SQL
                DECLARE CR CURSOR FOR
                SELECT JOB
                FROM EMPLOYEES
                WHERE JOB CONTAINING 'M'
                ORDER BY JOB;

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :Job;

        while (SQLCODE == 0){

                Count++;
                printf("%s\n",Job);
                Underline(80);

                EXEC SQL
                FETCH CR INTO :Job;
        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}

$ GPRE -e con027.e
$ CC FLAG_CC con027.c
$ LINK FLAG_LINK con027 
$ RUN con027
>> con027.qli
set semicolon;
ready WHERE_GDB:sh_test.gdb;
SELECT JOB
FROM EMPLOYEES
WHERE JOB CONTAINING 'M'
ORDER BY JOB;

FOR E IN EMPLOYEES SORTED BY E.JOB WITH E.JOB CONTAINING 'M' PRINT E.JOB;
FINISH;
QUIT;

$ QLI -n -a con027.qli
>> con027.sql
connect WHERE_GDB:sh_test.gdb;
SELECT JOB
FROM EMPLOYEES
WHERE JOB CONTAINING 'M'
ORDER BY JOB;
quit;
$ISQL -m -i con027.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE con027* 
