
$ GBAK -r WHERE_FILES:sh_join.gbk WHERE_GDB:sh_join_37.gdb
>> join037.e

/**********************************************************************
 Purpose:               Test SQL OUTER JOIN support in InterBase 4.0
 Description:           ON Null-col = Null-col
 Author:                Sam Hakim, June 1, 93
 ***********************************************************************
*/

#include <stdio.h>

DATABASE DB = "WHERE_GDB:sh_join_37.gdb";
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON st1.s1     t1s1;
BASED_ON st1.s2     t1s2;
BASED_ON st1.s3     t1s3;
BASED_ON st1.table_row   t1table_row;

BASED_ON st2.s1     t2s1;
BASED_ON st2.s2     t2s2;
BASED_ON st2.table_row   t2table_row;

char Test[]="\
select t.s1,t.s2,t.s3,t.table_row,x.s1,x.s2,x.table_row \
from (st1 t inner join st2 x on t.s1 = x.s1) \
where t.s1 is null";

void Underline();

main()
{
	
    int Count;
	Count = 0;
    printf ("Test:\n %s\n",Test);
    Underline(80);

    EXEC SQL
        DECLARE CR CURSOR FOR
        select t.s1,t.s2,t.s3,t.table_row,x.s1,x.s2,x.table_row
        from (st1 t inner join st2 x on t.s1 = x.s1)
        where t.s1 is null;

        EXEC SQL
		OPEN CR;
		
    EXEC SQL    FETCH CR INTO :t1s1,:t1s2,:t1s3,:t1table_row,
                :t2s1,:t2s2,:t2table_row;

        while (SQLCODE == 0){
		Count++;

                printf("%10d  ",t1s1);
                printf("%10d  ",t1s2);
                printf("%10d  ",t1s3);
                printf("%-10s  ",t1table_row);

                printf("%10d  ",t2s1);
                printf("%10d  ",t2s2);
                printf("%-10s\n",t2table_row);

                EXEC SQL
                FETCH CR INTO :t1s1,:t1s2,:t1s3,:t1table_row,
                :t2s1,:t2s2,:t2table_row;
        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;

exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}
$ GPRE -e join037.e
$ CC FLAG_CC join037.c
$ LINK FLAG_LINK join037 
$ RUN join037
>> join037.qli
ready WHERE_GDB:sh_join_37.gdb;
set semicolon;
set columns 100;

select t.s1,t.s2,t.s3,t.table_row,x.s1,x.s2,x.table_row
from (st1 t inner join st2 x on t.s1 = x.s1)
where t.s1 is null;

finish;
quit;
$ QLI -n -a join037.qli
>> join037.sql
connect WHERE_GDB:sh_join_37.gdb;
select t.s1,t.s2,t.s3,t.table_row,x.s1,x.s2,x.table_row
from (st1 t inner join st2 x on t.s1 = x.s1)
where t.s1 is null;
quit;
$ISQL -m -i join037.sql
$DROP WHERE_GDB:sh_join_37.gdb
$ DELETE join037* 
