
#/**********************************************************************
# Purpose:		Test predicates support in InterBase SQL 4.0
#
# Syntax:                <column spec> STARTING [WITH] <value spec>
#                        Case sensitive searches including blob string
#
# Description:           char-field, starting with string
#
#                        SELECT S1.CUSTNO, S1.TOTAL_VALUE, S1.PONUMB
#                        FROM SALES S1
#                        WHERE S1.PONUMB STARTING WITH '8902'
#                        ORDER BY S1.CUSTNO ASCENDING;
#
#
# Tables:                sales
#
# Author:		Sam Hakim, Feb 18, 93
# ***********************************************************************

$ GBAK -r WHERE_FILES:sh_test.gbk WHERE_GDB:sh_test.gdb
>> sta002.e

#include <stdio.h>

DATABASE DB = 'WHERE_GDB:sh_test.gdb';
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON SALES.CUSTNO           CustNo;
BASED_ON SALES.TOTAL_VALUE      Total_Value;
BASED_ON SALES.PONUMB           PoNumb;

char Test[]="SELECT S1.CUSTNO, S1.TOTAL_VALUE, S1.PONUMB \
FROM SALES S1 \
WHERE S1.PONUMB STARTING WITH '8902' \
ORDER BY S1.CUSTNO ASCENDING";

void Underline();

main(argc, argv)
int argc;
char *argv[];

{
	int Count = 0;
        printf("Test:\n%s\n",Test);
        Underline(80);


        EXEC SQL
                DECLARE CR CURSOR FOR
                    SELECT S1.CUSTNO, S1.TOTAL_VALUE, S1.PONUMB
                    FROM SALES S1
                    WHERE S1.PONUMB STARTING WITH '8902'
                    ORDER BY S1.CUSTNO ASCENDING;

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :CustNo, :Total_Value,:PoNumb;


        while (SQLCODE == 0){
		Count++;

                printf("%d\t",CustNo);
                printf("%8.2f\t",(double)(Total_Value));
                printf("%s\n",PoNumb);
                Underline(80);

                EXEC SQL
                FETCH CR INTO :CustNo, :Total_Value,:PoNumb;

        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;


exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}

/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}
$ GPRE -e sta002.e
$ CC FLAG_CC sta002.c
$ LINK FLAG_LINK sta002 
$ RUN sta002
>> sta002.sql
connect WHERE_GDB:sh_test.gdb;
SELECT S1.CUSTNO, S1.TOTAL_VALUE, S1.PONUMB 
FROM SALES S1 WHERE S1.PONUMB STARTING WITH '8902' 
ORDER BY S1.CUSTNO ASCENDING;
select count(*) from sales where ponumb starting with '8902';
quit;
$ISQL -m -i sta002.sql
$DROP WHERE_GDB:sh_test.gdb
$ DELETE sta002* 
