
$ GBAK -r WHERE_FILES:sh_join.gbk WHERE_GDB:sh_join_25.gdb
>> join025.e

/**********************************************************************
 Purpose:               Test SQL OUTER JOIN support in InterBase 4.0
 Description:           Outer join as subquery - Empty result set
 Author:                Sam Hakim, June 1, 93
 ***********************************************************************
*/

#include <stdio.h>

DATABASE DB = "WHERE_GDB:sh_join_25.gdb";
EXEC SQL	INCLUDE SQLCA;

EXEC SQL
        WHENEVER SQLERROR GO TO ERR_LBL;
EXEC SQL
        WHENEVER NOT FOUND GO TO NOMORE;

BASED_ON st1.s1     t1s1;
BASED_ON st1.s2     t1s2;
BASED_ON st1.table_row   t1table_row;

char Test[]="\
select x.s1,x.s2,x.table_row \
from st1 x where not exists \
(select a.s1 from \
(st1 a left join st2 b on a.s1 = b.s1) \
left join st3 c on c.s1 = b.s1 and c.s1 = 1)";

void Underline();

main()
{
	
    int Count;
	Count = 0;
    printf ("Test:\n %s\n",Test);
    Underline(80);

    EXEC SQL
                DECLARE CR CURSOR FOR
                select x.s1,x.s2,x.table_row
                from st1 x where not exists
                (select * from
                (st1 a left join st2 b on a.s1 = b.s1)
                left join st3 c on c.s1 = b.s1 and c.s1 = 1);

        EXEC SQL
		OPEN CR;
		
	EXEC SQL
                FETCH CR INTO :t1s1,:t1s2,:t1table_row;

        while (SQLCODE == 0){
		Count++;

                printf("%d  ",t1s1);
                printf("%d  ",t1s2);
                printf("%d\n",t1table_row);

                EXEC SQL
                FETCH CR INTO :t1s1,:t1s2,:t1table_row;
        }
	
NOMORE:
        EXEC SQL
                CLOSE CR;

	printf("\n\n* Total Records Listed >>> %d\n",Count);

	EXEC SQL
		COMMIT RELEASE;
	FINISH;

exit(0);

ERR_LBL:
	printf("Database error, SQLCODE = %d\n",SQLCODE);
        isc_print_status(gds__status);

	EXEC SQL
		ROLLBACK RELEASE;
	FINISH;

	exit(1);
}
/*--- print and underline of width i */

void Underline(i)
int i;
{
int j;

for (j=0;j<i;j++)
	printf("-");
printf("\n");

}
$ GPRE -e join025.e
$ CC FLAG_CC join025.c
$ LINK FLAG_LINK join025 
$ RUN join025
>> join025.sql
connect WHERE_GDB:sh_join_25.gdb;
select x.s1,x.s2,x.table_row
from st1 x where not exists
(select a.s1 from 
(st1 a left join st2 b on a.s1 = b.s1) left join st3 c on c.s1 = b.s1 and c.s1 = 1);
quit;
$ISQL -m -i join025.sql
$DROP WHERE_GDB:sh_join_25.gdb
$ DELETE join025* 
