#
# bug in devel-list
# Reported by Rudo Mihal 06-May-2004
# short example by Nickolay Samofatov
#
# Removed UDF test - deprecated. AP 2018
#

>> cf_isql_32.sql

create database 'WHERE_GDB:cf_isql_32.fdb' USER 'sysdba' PASSWORD 'masterkey';

select trim(TRAILING FROM (select max(rdb$relation_id) from rdb$database)) from rdb$database;

$ISQL -m -i cf_isql_32.sql
$DROP WHERE_GDB:cf_isql_32.fdb
$DELETE cf_isql_32*
