BRS 26-Apr-2004

bug #518349 isql show mangles relationship

$CREATE cf_isql_20a.sql

set echo;

CREATE DATABASE 'WHERE_GDB:cf_isql_20.fdb';

create table t(a int);
create table u(a int);
set term ^;
create trigger t for u after delete as begin
old.a=old.a; end^
commit ^

$CREATE cf_isql_20b.sql

set echo;
connect 'WHERE_GDB:cf_isql_20.fdb';
show table t;
show table u;

$ISQL -m -i cf_isql_20a.sql
$ISQL -m -i cf_isql_20b.sql
$ISQL -m -x WHERE_GDB:cf_isql_20.fdb
$DROP WHERE_GDB:cf_isql_20.fdb
$DELETE cf_isql_20*
