
/*
**  Name:		cf_isql_04
**  Series:		cf_isql
**  Meta-Series:
**  Dependencies:	None
**  Description:	This test is a level one test case for computed-fields.
**			
**			This test uses simple string operations when
**			defining computed-fields. This includes test cases
**			where computed-fields are string literals, which
**			really doesn't do any good. 
**
**			Using VARCHAR field.
**
**			This is the model of most of the tests defined here:
**
**			- Create a table with computed field.
**                      - Show table to verify the create table.
**			- Insert couple of rows with data.
**			- Query the table with matching expression and see
**			  if we get back same number of rows.
**			- Update a row.
**			- Query again using same expression as above.
**
**  Expected result:	For every set of testcase there will be two output lines.
**			
**			'Passed xx - Insert'
**			'Passed xx - Update'
**
**  Author:		Ravil A. Desai
**  Bugs:		6604 - Use of "|" as concat operator not recognized.
**  Change history:
**
*/

$ CREATE cf_test.sql
create database "WHERE_GDB:cf.gdb";

/*
** Syntax test cases - Valid string operations
*/

/*-----------------*/
/* Computed by (s) */
/*-----------------*/
create table t0  (s varchar(25), sc computed by (s));
show table t0;
insert into t0(s) values('computed');
insert into t0(s) values('(s)');
select 'Passed 1 - Insert' from t0 where sc = s having count(*) = 2;

update t0 set s = 'by' where s = 'computed';
select 'Passed 1 - Update' from t0 where sc = s having count(*) = 2;

/*--------------------*/
/* Computed by (s||s) */
/*--------------------*/
create table t5 (s varchar(25), sc computed by (s||s));
show table t5;
insert into t5(s) values('computed');
insert into t5(s) values('(s)');
select 'Passed 2 - Insert' from t5 where sc = s||s having count(*) = 2;

update t5 set s = 'by' where s = 'computed';
select 'Passed 2 - Update' from t5 where sc = s||s having count(*) = 2;

/*-------------------*/
/* Computed by (s|s) */
/*-------------------*/
/*
** Bug 6604: Use of "|" as concat operator not working
**
create table t10 (s varchar(25), sc computed by (s|s))
show table t10
insert into t10(s) values('computed')
insert into t10(s) values('(s)')
select 'Passed 3 - Insert' from t10 where sc = s|s having count(*) = 2

update t10 set s = 'by' where s = 'computed'
select 'Passed 3 - Update' from t10 where sc = s|s having count(*) = 2
*/

/*--------------------------*/
/* Computed by (s||' test') */
/*--------------------------*/
create table t15 (s varchar(25), sc computed by (s||' test'));
show table t15;
insert into t15(s) values('computed');
insert into t15(s) values('(s||'' test'')');
select 'Passed 4 - Insert' from t15 where sc = s||' test' having count(*) = 2;

update t15 set s = 'by' where s = 'computed';
select 'Passed 4 - Update' from t15 where sc = s||' test' having count(*) = 2;

/*--------------------------*/
/* Computed by ('test '||s) */
/*--------------------------*/
create table t20 (s varchar(25), sc computed by ('test '||s));
show table t20;
insert into t20(s) values('computed');
insert into t20(s) values('(''test ''||s)');
select 'Passed 5 - Insert' from t20 where sc = 'test '||s having count(*) = 2;

update t20 set s = 'by' where s = 'computed';
select 'Passed 5 - Update' from t20 where sc = 'test '||s having count(*) = 2;

/*-----------------------------------*/
/* Computed by ('test '||s||' test') */
/*-----------------------------------*/
create table t25 (s varchar(25), sc computed by ('test '||s||' test'));
show table t25;
insert into t25(s) values('computed');
insert into t25(s) values('(''test ''||s||'' test'')');
select 'Passed 6 - Insert' from t25 where sc = 'test '||s||' test' having count(*) = 2;

update t25 set s = 'by' where s = 'computed';
select 'Passed 6 - Update' from t25 where sc = 'test '||s||' test' having count(*) = 2;

/*----------------------*/
/* Computed by ('test') */
/*----------------------*/
create table t30 (s varchar(25), sc computed by ('test'));
show table t30;
insert into t30(s) values('computed');
insert into t30(s) values('(''test'')');
select 'Passed 7 - Insert' from t30 where sc = 'test' having count(*) = 2;

update t30 set s = 'by' where s = 'computed';
select 'Passed 7 - Update' from t30 where sc = 'test' having count(*) = 2;

/*--------------------------------*/
/* Computed by ('test '||' test') */
/*--------------------------------*/
create table t35 (s varchar(25), sc computed by ('test '||' test'));
show table t35;
insert into t35(s) values('computed');
insert into t35(s) values('(''test ''||'' test'')');
select 'Passed 8 - Insert' from t35 where sc = 'test '||' test' having count(*) = 2;

update t35 set s = 'by' where s = 'computed';
select 'Passed 8 - Update' from t35 where sc = 'test '||' test' having count(*) = 2;

drop database;
exit;

$ ISQL -m -input cf_test.sql
$ DELETE cf_test.sql
