
#
# BRS 04-Nov-2003
#
# bug #781610 problems with one line comments (--)
#

>> cf_isql_19.sql

CREATE DATABASE 'WHERE_GDB:cf_isql_19.fdb';

create table test (n integer);
insert into test values (1);

set echo;

-- I am a comment

/* BEGIN */
-- I am a comment
select * from test;
/* END */

/* BEGIN */
-- comment with unclosed 'quoted string
select * from test;
/* END */

/* BEGIN */
-- comment with unclosed "quoted string
select * from test;
/* END */

/* BEGIN */
-- I am a comment;
select * from test;
/* END */

/* BEGIN with unclosed "quoted */
-- I am a comment;
select * from test;
/* END */

select * /*
comment
*/
from test;

select * 
/* comment */
from test;

select * 
-- comment
from test;

/*
Comment
*/ select * from test;


$ISQL -m -i cf_isql_19.sql
$DROP WHERE_GDB:cf_isql_19.fdb
$DELETE cf_isql_19.sql
