#
#  The contents of this file are subject to the Initial
#  Developer's Public License Version 1.0 (the "License");
#  you may not use this file except in compliance with the
#  License. You may obtain a copy of the License at
#  http://www.ibphoenix.com/main.nfs?a=ibphoenix&page=ibp_idpl.
#
#  Software distributed under the License is distributed AS IS,
#  WITHOUT WARRANTY OF ANY KIND, either express or implied.
#  See the License for the specific language governing rights
#  and limitations under the License.
#
#  The Original Code was created by Alex Peshkoff
#  for the Firebird Open Source RDBMS project.
#
#  Copyright (c) 2009 Alex Peshkoff <peshkoff@mail.ru>
#  and all contributors signed below.
#
#  All Rights Reserved.
#  Contributor(s): ______________________________________.
#

#
# Minimum grant test
#

>> cf_isql_35.sql

set list;

CREATE DATABASE 'WHERE_GDB:cf_isql_35.fdb';

recreate table test( d decfloat );
commit;
insert into test select 15514 from rdb$types rows 3;
commit;
select distinct d as d_distinct from test;

with A(val) as (
  select cast(15514 as decfloat) from rdb$database union all
  select cast(15514 as decfloat) from rdb$database union all
  select cast(15514 as decfloat) from rdb$database
)
select distinct val from A;

recreate table test0(n decfloat);
commit;

insert into test0 values( 0 );
insert into test0 values( 0 );
commit;

select n as test0_n from test0;
commit;

select n as n_grouped_from_test0 from test0 group by 1; --- [ 1 ]

select distinct n as n_uniq_from_test0 from test0; -- [ 2 ]

select count(distinct n) as count_uniq_from_test0 from test0; -- [ 3 ]

$ISQL -m -i cf_isql_35.sql
$DROP WHERE_GDB:cf_isql_35.fdb
$DELETE cf_isql_35*
