BRS 26-Apr-2004

bug #223513 ambiguity between tables and views

$CREATE cf_isql_22a.sql

set echo;

CREATE DATABASE 'WHERE_GDB:cf_isql_22.fdb';

create table t(a int);
create view v as select a from t;

$CREATE cf_isql_22b.sql

set echo;
connect 'WHERE_GDB:cf_isql_22.fdb';
show tables;
show views;
show table v;
show table t;
show view v;
show view t;

$ISQL -m -i cf_isql_22a.sql
$ISQL -m -i cf_isql_22b.sql
$ISQL -m -x WHERE_GDB:cf_isql_22.fdb
$DROP WHERE_GDB:cf_isql_22.fdb
$DELETE cf_isql_22*
