
#
#  Name:		cf_isql_12
#  Series:		cf_isql
#  Meta-Series:
#  Dependencies:	None
#  Description:	This test is a level two test case for computed-fields.
#			
#			This test checks for defining computed-field using columns
#			that themself are computed fields.
#
#  Expected result:	
#			
#  Author:		Ravil A. Desai
#  Change history:
#			 cloned for V6.x FSG 16.Oct:00
#

>> cf_test.sql
create database "WHERE_GDB:cf.gdb";

/*---------------------------------------------*/
/* Computed field using another computed field */
/*---------------------------------------------*/
create table t3 (a integer, af computed by (a*3), afaf computed by (af*2));
insert into t3(a) values(10);
select * from t3;

exit;

$ ISQL -m -input cf_test.sql
$ DROP WHERE_GDB:cf.gdb
$ DELETE cf_test.sql
