
#
#  Name:		cf_isql_16
#  Series:		cf_isql
#  Meta-Series:
#  Dependencies:	None
#  Description:	This test is a level two test case for computed-fields.
#			
#			This test checks to see if additional column attributes
#			such as DEFAULT, NOT NULL, COLLATE and <col-constraints>
#			are allowed for computed-field columns.
#
#  Expected result:	The create table definitions should fail.
#			
#  Author:		Ravil A. Desai
#  Change history:
#			 cloned for V6.x FSG 16.Oct:00
#

>> cf_test.sql
create database "WHERE_GDB:cf.gdb";

/*-------------------------------------------------------------*/
/* Create a table with computed field and improper attributes. */
/*-------------------------------------------------------------*/
create table t0 (a integer, af computed by (a*3) default 10);
create table t1 (a integer, af computed by (a*3) not null);
create table t2 (a char(5), af computed by (a||a) collate DOS850);
create table t3 (a integer, af computed by (a*3) check (a > 3));

create table t4 (a integer);
create table t4r (a integer, af computed by (a*3) references t4(a));

create table t5 (a integer, af computed by (a*3) unique);
create table t6 (a integer, af computed by (a*3) primary key);

show tables;
exit;
$ISQL -m -input cf_test.sql
$ DROP WHERE_GDB:cf.gdb
$ DELETE cf_test.sql
