
#
#  Name:		cf_isql_06
#  Series:		cf_isql
#  Meta-Series:
#  Dependencies:	None
#  Description:	This test is a level one test case for computed-fields.
#			
#			This test defines a computed-field which is dependent on
#			more than one columns of a same type. In this case an
#			integer fields.
#
#			This is the model of most of the tests defined here:
#
#			- Create a table with computed field.
#                      - Show table to verify the create table.
#			- Insert couple of rows with data.
#			- Query the table with matching expression and see
#			  if we get back same number of rows.
#			- Update a row.
#			- Query again using same expression as above.
#
#  Expected result:	For every set of testcase there will be two output lines.
#			
#			'Passed xx - Insert'
#			'Passed xx - Update'
#
#  Author:		Ravil A. Desai
#  Bugs:		
#  Change history:
#
#

>> cf_test.sql
create database "WHERE_GDB:cf.gdb";

/*
** Test case which defines computed field on more than one column
*/

/*-------------------*/
/* Computed by (a*b) */
/*-------------------*/
create table t0 (a integer, b integer, a_b computed by (a*b));
show table t0;
insert into t0(a,b) values(10,10);
insert into t0(a,b) values(11,11);
select 'Passed 1 - Insert' from t0 where a_b = a*b having count(*) = 2;

update t0 set a = 12, b = 12 where a = 10;
update t0 set a = 13         where a = 11;
select 'Passed 1 - Update' from t0 where a_b = a*b having count(*) = 2;

/*---------------------*/
/* Computed by (a*b/c) */
/*---------------------*/
create table t5 (a integer, b integer, c integer, a_b_c computed by (a*b/c));
show table t5;
insert into t5(a,b,c) values(10,10,10);
insert into t5(a,b,c) values(11,11,11);
select 'Passed 2 - Insert' from t5 where a_b_c = a*b/c having count(*) = 2;

update t5 set a = 12, b = 12, c = 12 where a = 10;
update t5 set a = 13                 where a = 11;
select 'Passed 2 - Update' from t5 where a_b_c = a*b/c having count(*) = 2;

/*----------------------*/
/* Computed by (a/10*b) */
/*----------------------*/
create table t10 (a integer, b integer, a_b_const computed by (a/10*b));
show table t10;
insert into t10(a,b) values(10,10);
insert into t10(a,b) values(11,11);
select 'Passed 3 - Insert' from t10 where a_b_const = a/10*b having count(*) = 2;

update t10 set a = 12, b = 12 where a = 10;
update t10 set a = 13         where a = 11;
select 'Passed 3 - Update' from t10 where a_b_const = a/10*b having count(*) = 2;

exit;

$ ISQL -m -input cf_test.sql
$ DROP WHERE_GDB:cf.gdb
$ DELETE cf_test.sql
