
>> define.sql

create database "WHERE_GDB:index.gdb";
 
create domain fld1 smallint;
create domain fld2 varchar(25);

create table data_table1 (
  fld1 fld1,
  fld2 fld2
);

create unique index idx1_1 on data_table1 (fld1);
create index idx1_2 on data_table1 (fld1);
create desc index idx1_3 on data_table1 (fld1);
create asc index idx1_4 on data_table1 (fld1);

>> init1.sql

connect 'WHERE_GDB:index.gdb';

show indexes;

insert into data_table1 (fld1, fld2) values (1, 'one');
insert into data_table1 (fld1, fld2) values (2, 'two');
insert into data_table1 (fld1, fld2) values (3, 'three');

select fld1, fld2 from data_table1 order by fld1;
select fld1, fld2 from data_table1 order by fld1 desc;
select fld1, fld2 from data_table1 order by fld1 asc;

exit;

>> init2.sql

connect 'WHERE_GDB:index.gdb';
create table data_table2(
fld1 integer not null,
fld2 varchar(10) not null
);
create unique index idx2_1 on data_table2(fld1);
create index idx2_2 on data_table2(fld1);
create desc index idx2_3 on data_table2(fld1);
create asc  index idx2_4 on data_table2(fld1);

show index;

insert into data_table2 values(1,'one');
insert into data_table2 values(2,'two');
insert into data_table2 values(3,'three');

select * from data_table1 order by fld1;
select * from data_table1 order by fld1 desc;
select * from data_table1 order by fld1 asc;

select * from data_table2 order by fld1;
select * from data_table2 order by fld1 desc;
select * from data_table2 order by fld1 asc;

drop database;
exit;

$ISQL -q -m -i define.sql
$ISQL -m -i init1.sql
$ISQL -m -i init2.sql
$DELETE init1.*
$DELETE init2.*
