
/*******************************************************************************
 Test Name:   dsql_domain_12
 Series Name: dsql_domains
 Date:        18-Oct-1993
 Related Bugs:  bug_5537 - problem with decimal fields, removed from test.
 Comment:     This script will run level 1 testing, checking syntax of create 
              domain using datatype and default clauses, then creating a table 
              using the domain fields and inserting data to those fields, 
              allowing missing data to be supplied by the default definitions 
              for the domain.
*******************************************************************************/
HISTORY:

$ GBAK -r WHERE_FILES:atlas.gbak WHERE_GDB:atlas.gdb
$ CREATE domain_12.sql
create domain dom12a1 as smallint
 default 0;
create domain dom12b1 as integer
 default 0;
create domain dom12c1 as date
 default '12-12-57';
create domain dom12d1 as char(30)
 default 'generic username';
create domain dom12e1 as varchar(4)
 default null;
create domain dom12f1 as varchar(10)
 default 'default';
create domain dom12g1 as float
 default 0;
create domain dom12h1 as double precision
 default null;
create table tab12a 
 (fld1 dom12a1, fld2 dom12b1, fld3 dom12c1, fld4 dom12d1,
  fld5 dom12e1, fld6 dom12f1, fld7 dom12g1, fld8 dom12h1);
show table tab12a;
insert into tab12a (fld1) values (100);
insert into tab12a (fld2) values (200);
insert into tab12a (fld3) values ('01/27/92');
insert into tab12a (fld4) values ('Testing insert to field 4 xxxx');
insert into tab12a (fld5) values ('Test');
insert into tab12a (fld6) values ('no default');
insert into tab12a (fld7) values (50.02);
insert into tab12a (fld8) values (10000);
commit;
select * from tab12a;
exit;
$ isql -m WHERE_GDB:atlas.gdb -i domain_12.sql
$ DROP WHERE_GDB:atlas.gdb
$ DELETE domain_12.sql
