
#/*******************************************************************************
# Test Name:   dsql_domain_01
# Series Name: dsql_domains
# Date:        4-October-1993
# Comments:    This script will test the level 0 syntax for SQL create domain,
#              defining only the datatype.
# History:     Cloning test for 6.0. Eliminating "DEC(25,10)" domain definition
#              since it is no longer valid for 6.0 (stsikin, 10-Dec-1998)
#*******************************************************************************/
#HISTORY:

$ GBAK -r WHERE_FILES:atlas.gbak WHERE_GDB:atlas.gdb
>> domain_01a.sql
create domain dom01a_1 as smallint;
commit;
show domain dom01a_1;
create domain dom01a_2 as numeric(3,1);
commit;
show domain dom01a_2;
create domain dom01b_1 as integer;
commit;
show domain dom01b_1;
create domain dom01b_2 as int;
commit;
show domain dom01b_2;
create domain dom01b_3 as numeric;
commit;
show domain dom01b_3;
create domain dom01b_4 as numeric(6,2);
commit;
show domain dom01b_4;
create domain dom01c as date;
commit;
show domain dom01c;
create domain dom01d_1 as char(20);
commit;
show domain dom01d_1;
create domain dom01d_2 as character(99);
commit;
show domain dom01d_2;
create domain dom01e_1 as varchar(25);
commit;
show domain dom01e_1;
create domain dom01e_2 as character varying(100);
commit;
show domain dom01e_2;
create domain dom01e_3 as char varying(2);
commit;
show domain dom01e_3;
create domain dom01f_1 as decimal(6,2);
commit;
show domain dom01f_1;
create domain dom01g_1 as float;
commit;
show domain dom01g_1;
create domain dom01g_2 as long float;
commit;
show domain dom01g_2;
create domain dom01g_3 as real;
commit;
show domain dom01g_3;
create domain dom01h as double precision;
commit;
show domain dom01h;
create domain dom01i_1 as blob;
commit;
show domain dom01i_1;
create domain dom01i_2 as blob(60,1);
commit;
show domain dom01i_2;
exit;
/*******************************************************************************
 This section of the script will check the boundaries for domain names and 
 attempt to use illegal syntax.
*******************************************************************************/

>> domain_01b.sql
create domain long_domain_name_of_63_charsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx as integer;
commit;
show domain long_domain_name_of_63_charsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
create domain long_domain_name_more_than_63_charactersxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx as char(10);
commit;
create domain 23456789_domain as double;
commit;
create domain $_domain as blob;
commit;
create domain dom01a_1 as char(5);
commit;
create domain dom01j as rubbish;
commit;
create domain table as blob;
commit;
exit;
$ isql -m WHERE_GDB:atlas.gdb -i domain_01a.sql
$ isql -m WHERE_GDB:atlas.gdb -i domain_01b.sql
$ DROP WHERE_GDB:atlas.gdb
$ DELETE domain_01*
