
$CREATE COMMENT
*******************************************************************************
 
Test Name:  	EXT_REL_0_36_D
Test Level:     0
Series Name:    EXT_LEV_0
Date:  		July 3, 1994
Author:  	Scott Van Voris
Bug: 
Description:    This is a Level 0 test which is designed to verify that
		two external tables with the same name cannot be created
		in the same database.

 
Expected Output:        Use CONNECT or CREATE DATABASE to specify a database
  			Statement failed, SQLCODE = -607
 
			unsuccessful metadata update
			-Table EXT_TABLE already exists
			Use CONNECT or CREATE DATABASE to specify a database
			Database:  ext_rel_0_36_D.gdb
			FIELD1                          CHAR(10) Nullable 
History:
2-Oct-95:  Mark
  Removed the Cleanup / Setup comments from the test.
  Also, added WHERE_GDB and RUN drop_gdb to the tests. 

3-Oct-95: Marco
  Added the WHERE_GDB_EXTERNAL, so the external file can be created 
  by the server in the correct place when accessing data remotely.
  Also, I removed any referance to DIR external.dat and TYPE external.dat
  which would also fail when running remotely.

*******************************************************************************

$CREATE isql.in

CREATE DATABASE "WHERE_GDB:ext_rel_0_36_D.gdb";

CREATE TABLE ext_table EXTERNAL FILE 'WHERE_GDB_EXTERNAL:external.dat'
       (field1 CHARACTER(10)) ;

CREATE TABLE ext_table EXTERNAL FILE 'WHERE_GDB_EXTERNAL:external.dat'
       (field1 CHARACTER(10)) ;

$CREATE isql2.in

CONNECT "WHERE_GDB:ext_rel_0_36_D.gdb";
SHOW TABLE ext_table;

$ISQL -m -input isql.in
$ISQL -m -input isql2.in
$DROP WHERE_GDB:ext_rel_0_36_D.gdb
$DELETE_REM WHERE_GDB: WHERE_GDB_EXTERNAL: external.dat
$DELETE COMMENT isql.in isql2.in
