
#*******************************************************************************
# 
#Test Name:  	EXT_REL_0_30_D
#Test Level:     0
#Series Name:    EXT_LEV_0
#Date:  		July 3, 1994
#Author:  	Scott Van Voris
#Description:    This is a Level 0 test which is designed to verify that 
#		a column created in an external file is not created with
#		an automatic index.
#
#		In this case a foreign key is the cause of the index.
#		(REFERENCES.)
# 
#Expected Output:        Use CONNECT or CREATE DATABASE to specify a database
#			Statement failed, SQLCODE = -902
# 
#			external.dat
#			Use CONNECT or CREATE DATABASE to specify a database
#			Database:  ext_rel_0_30_D.gdb
#History:
#2-Oct-95:  Mark
#  Removed the Cleanup / Setup comments from the test.
#  Also, added WHERE_GDB and RUN drop_gdb to the tests.
#
#3-Oct-95: Marco
#  Added the WHERE_GDB_EXTERNAL, so the external file can be created 
#  by the server in the correct place when accessing data remotely.
#  Also, I removed any referance to DIR external.dat and TYPE external.dat
#  which would also fail when running remotely.
#
#14-Oct-00: Frank Schlottmann-Goedde
#  replaced double with single quotes where necessary to run with version 6.x
#
#*******************************************************************************

>> isql.in

CREATE DATABASE 'WHERE_GDB:ext_rel_0_30_D.gdb';

CREATE TABLE int_table
        (field1 SMALLINT NOT NULL PRIMARY KEY);
 
CREATE TABLE ext_table EXTERNAL FILE 'WHERE_GDB_EXTERNAL:external.dat'
        (field1 SMALLINT NOT NULL REFERENCES int_table (field1),
         field2 SMALLINT);

>> isql2.in

CONNECT 'WHERE_GDB:ext_rel_0_30_D.gdb';

SHOW TABLE ext_table;

$ISQL -m -input isql.in
$ISQL -m -input isql2.in
$DROP WHERE_GDB:ext_rel_0_30_D.gdb
$DELETE_REM WHERE_GDB: WHERE_GDB_EXTERNAL: external.dat
$DELETE isql.in isql2.in
