
$CREATE COMMENT
*******************************************************************************
 
Test Name:  	EXT_REL_0_7_D
Test Level:     0
Series Name:    EXT_LEV_0
Date:  		June 28, 1994
Author:  	Scott Van Voris
Bug: 
 
Description:    This is a Level 0 test which is designed to verify the 
		syntax to create an external relation with a fixed-length
		datatype is working properly.

                In order to verify the external relation was really 
                created, a tuple is inserted into the relation, and the 
                value in the relation retreived via a query.
 
Expected Output:        Use CONNECT or CREATE DATABASE to specify a database
			external.dat
			Use CONNECT or CREATE DATABASE to specify a database
			Database:  ext_rel_0_7_D.gdb

			                FIELD1 
			====================== 
 
			          3.1415926536 
History:

2-Oct-95:  Mark
  Removed the Cleanup / Setup comments from the test.
  Also, added WHERE_GDB and RUN drop_gdb to the tests.

3-Oct-95: Marco
  Added the WHERE_GDB_EXTERNAL, so the external file can be created 
  by the server in the correct place when accessing data remotely.
  Also, I removed any referance to DIR external.dat and TYPE external.dat
  which would also fail when running remotely.

14-Oct-00: Frank Schlottmann-Goedde
  replaced double with single quotes where necessary to run with version 6.x
 
*******************************************************************************

$CREATE isql.in

CREATE DATABASE 'WHERE_GDB:ext_rel_0_7_D.gdb';

CREATE TABLE ext_table EXTERNAL FILE 'WHERE_GDB_EXTERNAL:external.dat'
        (field1 DECIMAL(10,10)) ;
 
$CREATE isql2.in

CONNECT 'WHERE_GDB:ext_rel_0_7_D.gdb';
INSERT INTO ext_table (field1) VALUES (3.14159265358979326);
SELECT * FROM ext_table;

$ISQL -input isql.in
$ISQL -input isql2.in
$DROP WHERE_GDB:ext_rel_0_7_D.gdb
$DELETE_REM WHERE_GDB: WHERE_GDB_EXTERNAL: external.dat
$DELETE COMMENT isql.in isql2.in
