
#*******************************************************************************
#
#Test Name:  	EXT_REL_0_33_E
#Test Level:     0
#Series Name:    EXT_LEV_0
#Date:  		July 5, 1994
#Author:  	Scott Van Voris
#Bug:
#Description:    This is a Level 0 test which is designed to verify that
#                a table created in an external file is not created with
#                an automatic index.
#
#                In this case 'UNIQUE' is the cause of the index.
#
#Expected Output:       **  We should get some appropriate error message and
#			InterBase should gracefully exit without creating
#			the index (or table?).  **
#History:
#2-Oct-95:  Mark
#  Removed the Cleanup / Setup comments from the test.
#  Also, added WHERE_GDB and RUN drop_gdb to the tests.
#
#3-Oct-95: Marco
#  Added the WHERE_GDB_EXTERNAL, so the external file can be created
#  by the server in the correct place when accessing data remotely.
#  Also, I removed any referance to DIR external.dat and TYPE external.dat
#  which would also fail when running remotely.
#
#*******************************************************************************

>> column.e
#include <stdio.h>
#include <stdlib.h>

EXEC SQL
    INCLUDE SQLCA

EXEC SQL
    WHENEVER SQLERROR GO TO ERR_LBL;


int main()
{

EXEC SQL
   CREATE DATABASE "WHERE_GDB:ext_rel_0_33_E.gdb";

EXEC SQL
   CREATE TABLE ext_table EXTERNAL FILE "WHERE_GDB_EXTERNAL:external.dat"
        (field1 SMALLINT NOT NULL,
         field2 SMALLINT,
         CONSTRAINT uniq_key UNIQUE(field1));

return 0;
ERR_LBL:
	EXEC SQL WHENEVER SQLERROR CONTINUE;
	printf ("Data base error, SQLCODE = %d\n", SQLCODE);
	isc_print_status (gds__status);

    EXEC SQL
        ROLLBACK RELEASE;

    return 1;
}
>> isql.in

CONNECT "WHERE_GDB:ext_rel_0_33_E.gdb";
SHOW TABLE ext_table;

$GPRE column.e
$CC FLAG_CC column.c
$LINK FLAG_LINK column
$RUN column
$ISQL -m -input isql.in
$DROP WHERE_GDB:ext_rel_0_33_E.gdb
$DELETE_REM WHERE_GDB: WHERE_GDB_EXTERNAL: external.dat
$DELETE isql.in column*
