
#******************************************************************************
# 
#Test Name:  	EXT_REL_0_33_G
#Test Level:     0
#Series Name:    EXT_LEV_0
#Date:  		July 5, 1994
#Author:  	Scott Van Voris
# 
#Description:    This is a Level 0 test which is designed to verify that 
#		a table created in an external file is not created with
#		an automatic index.
#
#		In this case 'UNIQUE' is the cause of the index.
# 
#history:
#15-May-95:      failing. had no init record and when I initialized it, it
#		fails on the index create. Either due to the UNIQUE or to the
#		DDL for index.
#
#Expected Output: produces an error on create index stmt. Doubt that this
#                is what the test had in mind, but GDEF doesn't like the
#		define index in the same program w/the define table.
#History:
#2-Oct-95:  Mark
#  Removed the Cleanup / Setup comments from the test.
#  Also, added WHERE_GDB and RUN drop_gdb to the tests.		
#
#3-Oct-95: Marco
#  Added the WHERE_GDB_EXTERNAL, so the external file can be created 
#  by the server in the correct place when accessing data remotely.
#  Also, I removed any referance to DIR external.dat and TYPE external.dat
#  which would also fail when running remotely.
#2-Nov-95: clare
#  commented out the ISQL command since the test fails on the .gdl execute.
#  NCR was producing a slightly different result and I am trying to eliminate
#  a local init.  Actually, the global init is outdated.  We must not have
#  reinitialized this test w/the V4.0 certification runs.  A new and improved
#  error occurs due to the index create in gdef.  Trying this test w/TMP set
#  will core dump!! Apparently TMP doesn't work w/QLI or GDEF (at least not
#  on NCR).
#
#*******************************************************************************

>> create.gdl

DEFINE DATABASE "WHERE_GDB:ext_rel_0_33_G.gdb";

DEFINE RELATION ext_table EXTERNAL_FILE "WHERE_GDB_EXTERNAL:external.dat"
        field1 SHORT,
        field2 SHORT;
DEFINE INDEX ext_table_idx for ext_table
	unique field1;

>> isql2.in

CONNECT "WHERE_GDB:ext_rel_0_33_G.gdb";

SHOW TABLE ext_table;

$GDEF create.gdl
#ISQL -m -input isql2.in
$DROP WHERE_GDB:ext_rel_0_33_G.gdb
$DELETE_REM WHERE_GDB: WHERE_GDB_EXTERNAL: external.dat
$DELETE create.gdl isql2.in
