
$CREATE comment
*******************************************************************************
 
Test Name:  	EXT_REL_0_20_D
Test Level:     0
Series Name:    EXT_LEV_0
Date:  		July 1, 1994
Author:  	Scott Van Voris
Bug:		6978 
 
Description:    This is a Level 0 test which is designed to verify an 
		error is returned when an external relation with a 
		variable-length datatype is created.

		The database is connected and the tables existing in
		the database are checked to make sure the external relation
		was not created.  We also check to make sure the external
		file was not created.
 
Expected Output:        *** Since variable length datatypes are not allowed
                        for external relations, we should get an error.

			(Update 1994-December-2 David Schnepper )
			VARCHAR is fine in an external relation, only
			BLOB & array are not allowed.
History:
2-Oct-95:  Mark
  Removed the Cleanup / Setup comments from the test.
  Also, added WHERE_GDB and RUN drop_gdb to the tests.

3-Oct-95: Marco
  Added the WHERE_GDB_EXTERNAL, so the external file can be created 
  by the server in the correct place when accessing data remotely.
  Also, I removed any referance to DIR external.dat and TYPE external.dat
  which would also fail when running remotely.

*******************************************************************************

$CREATE isql.in 

CREATE DATABASE "WHERE_GDB:ext_rel_0_20_D.gdb";
 
CREATE TABLE ext_table EXTERNAL FILE 'WHERE_GDB_EXTERNAL:external.dat'
   (field1 VARCHAR(10)) ;

$CREATE isql2.in

CONNECT "WHERE_GDB:ext_rel_0_20_D.gdb";

SHOW TABLE ext_table;

$ISQL -m -input isql.in
$ISQL -m -input isql2.in
$DROP WHERE_GDB:ext_rel_0_20_D.gdb
$DELETE_REM WHERE_GDB: WHERE_GDB_EXTERNAL: external.dat
$DELETE comment isql.in isql2.in
