>> fb_name_resolution_01_1.sql
create database "WHERE_GDB:fb_name_resolution_01.fdb";

set term !;

create package pkg1
as
begin
    procedure p1 returns (o varchar(50));
    procedure p1a returns (o varchar(50));
    procedure p1b returns (o varchar(50));
    procedure p1c returns (o varchar(50));
    procedure p2 returns (o varchar(50));
    procedure p2a returns (o varchar(50));
    procedure p2b returns (o varchar(50));
    procedure p2c returns (o varchar(50));
    function f1 returns varchar(50);
    function f1a returns varchar(50);
    function f1b returns varchar(50);
    function f1c returns varchar(50);
    function f2 returns varchar(50);
end!

create package body pkg1
as
begin
    procedure p1 returns (o varchar(50))
    as
    begin
        o = 'pkg1.p1';
        suspend;
    end

    procedure p1a returns (o varchar(50))
    as
    begin
        execute procedure p1 returning_values o;
        suspend;
    end

    procedure p1b returns (o varchar(50))
    as
    begin
        execute procedure pkg1.p1 returning_values o;
        suspend;
    end

    procedure p1c returns (o varchar(50))
    as
    begin
        execute procedure pkg1%package.p1 returning_values o;
        suspend;
    end

    procedure p2 returns (o varchar(50))
    as
    begin
        o = 'pkg1.p2';
        suspend;
    end

    procedure p2a returns (o varchar(50))
    as
    begin
        select * from p2 into o;
        suspend;
    end

    procedure p2b returns (o varchar(50))
    as
    begin
        select * from pkg1.p2 into o;
        suspend;
    end

    procedure p2c returns (o varchar(50))
    as
    begin
        select * from pkg1%package.p2 into o;
        suspend;
    end

    function f1 returns varchar(50)
    as
    begin
        return 'pkg1.f1';
    end

    function f1a returns varchar(50)
    as
    begin
        return f1();
    end

    function f1b returns varchar(50)
    as
    begin
        return pkg1.f1();
    end

    function f1c returns varchar(50)
    as
    begin
        return pkg1%package.f1();
    end

    function f2 returns varchar(50)
    as
    begin
        return 'pkg1.f2';
    end
end!

set term ;!

---

execute procedure pkg1.p1;
execute procedure pkg1%package.p1;

select * from pkg1.p1;
select * from pkg1%package.p1;

execute procedure pkg1.p1a;
execute procedure pkg1.p1b;
execute procedure pkg1.p1c;

execute procedure pkg1.p2;
execute procedure pkg1%package.p2;

select * from pkg1.p2a;
select * from pkg1.p2b;
select * from pkg1.p2c;

select pkg1.f1() from rdb$database;

select pkg1.f1a() from rdb$database;
select pkg1.f1b() from rdb$database;
select pkg1.f1c() from rdb$database;

select pkg1%package.f1() from rdb$database;

select pkg1.f2() from rdb$database;
select pkg1%package.f2() from rdb$database;

exit;

$ ISQL -q -m -e -i fb_name_resolution_01_1.sql
$ DELETE fb_name_resolution_01_1*
$ DROP WHERE_GDB:fb_name_resolution_01.fdb
