>> fb_sql_returning_2.sql
create database "WHERE_GDB:returning.fdb";

set term !;

---

create table tab (
  n1 integer primary key,
  n2 integer
)!

insert into tab values (1, 10) returning n1, n2!
insert into tab values (2, 20) returning n1, n2!

update tab set n2 = n2 * 10 returning n1, n2, new.n1, new.n2, old.n1, old.n2!

update tab set n2 = n2 * 10 where n1 = 0 returning n1, n2, new.n1, new.n2, old.n1, old.n2!

update tab set n2 = n2 * 10 where n1 = 2 returning n1, n2, new.n1, new.n2, old.n1, old.n2!

update or insert into tab values (2, 2000) returning n1, n2, new.n1, new.n2, old.n1, old.n2!
update or insert into tab values (3, 3000) returning n1, n2, new.n1, new.n2, old.n1, old.n2!

delete from tab returning n1, n2!

delete from tab where n1 = 1 returning n1, n2!
delete from tab where n1 = 1 returning n1, n2!

---

set term ;!

exit;

$ ISQL -q -m -e -i fb_sql_returning_2.sql
$ DELETE fb_sql_returning_2*
$ DROP WHERE_GDB:returning.fdb
