>> fb_sql_window_func_03.sql
connect "WHERE_GDB:winfunc.fdb";

---

select
    p.*,
    dense_rank() over (order by id),
    dense_rank() over (order by id desc),
    rank() over (order by id),
    rank() over (order by id desc),
    row_number() over (order by id),
    row_number() over (order by id desc)
  from persons p
  order by id;

select
    e.*,
    dense_rank() over (order by val nulls first),
    rank() over (order by val nulls first),
    row_number() over (order by val nulls first)
  from entries e
  order by id;

select
    e.*,
    dense_rank() over (partition by person order by val nulls first, dat nulls first),
    rank() over (partition by person order by val nulls first, dat nulls first),
    row_number() over (partition by person order by val nulls first, dat nulls first)
  from entries e
  order by id;

select
    person,
    sum(dr),
    sum(r),
    sum(rn)
  from (
    select
        e.*,
        dense_rank() over (partition by person) dr,
        rank() over (partition by person) r,
        row_number() over (partition by person) rn
      from entries e
  ) x
  group by
    person
  order by person;

select
    sum(dr),
    sum(r),
    sum(rn)
  from (
    select
        e.*,
        dense_rank() over (partition by person) dr,
        rank() over (partition by person) r,
        row_number() over (partition by person) rn
      from entries e
  ) x;

select
    id,
    person,
    dat,
    val,
    sum(rn) srn,
    row_number() over (order by id)
  from (
    select
        e.*,
        row_number() over (partition by person order by id) rn
      from entries e
  ) x
  group by
    id,
    person,
    dat,
    val
  order by id;

---

exit;

$ ISQL -q -m -e -i fb_sql_window_func_03.sql
$ DELETE fb_sql_window_func_03*
