#
#HISTORY:
#19-May-2001  Neil McCalden    New test created.
#
#20-Feb-2018	Alex Peshkoff	Test UDR instead UDF.
#
#Purpose:		Test group by a udf function 
#
#Description:     Group by a udf function on base table
#
# Author:          Neil McCalden, Alex Peshkoff
#

$ GBAK -r WHERE_FILES:atlas.gbk WHERE_GDB:atlas.gdb
$ISQL -m WHERE_GDB:atlas.gdb -i WHERE_EXAMPLES:udf_compat.sql
>> grpview.sql
connect WHERE_GDB:atlas.gdb;
create view udfgrp_view
(first_name,last_name,state,sname)
as
select first_name,last_name,state,dow(init_term)
from mayors;
quit;
$ISQL -m -i grpview.sql
>> udfgrp1.sql
connect WHERE_GDB:atlas.gdb;
SELECT DOW(INIT_TERM) AS DOW_INITTERM, COUNT(*)
FROM MAYORS
GROUP BY DOW(INIT_TERM);
quit;
$ISQL -m -i udfgrp1.sql
>> udfgrp2.sql
connect WHERE_GDB:atlas.gdb;
select sname,count(*) from udfgrp_view
group by sname;
quit;
$ISQL -m -i udfgrp2.sql
>> udfgrp3.sql
connect WHERE_GDB:atlas.gdb;
SELECT STATE, DOW(INIT_TERM) AS DOW_INITTERM, COUNT(*)
FROM MAYORS
GROUP BY STATE, DOW(INIT_TERM);
quit;
$ISQL -m -i udfgrp3.sql
>> udfgrp4.sql
connect WHERE_GDB:atlas.gdb;
select state,sname,count(*) from udfgrp_view
group by state,sname;
quit;

$ISQL -m -i udfgrp4.sql
$DROP WHERE_GDB:atlas.gdb
$DELETE grpview.sql udfgrp*
