>> fb_sql_subproc_1.sql
set names iso8859_1;
create database "WHERE_GDB:subproc.fdb";

set term !;

---

create procedure p1 returns (o1 integer)
as
	declare procedure sub1 returns (o1 integer)
	as
	begin
		o1 = 1;
		suspend;
		o1 = 2;
		suspend;
		o1 = 3;
		suspend;
	end
begin
	execute procedure sub1 returning_values o1;
	suspend;

	for select o1 from sub1 into o1 do
		suspend;
end!

select * from p1!

---

execute block returns (o1 integer)
as
	declare procedure sub1 returns (o1 integer)
	as
	begin
		o1 = 1;
		suspend;
		o1 = 2;
		suspend;
		o1 = 3;
		suspend;
	end
begin
	execute procedure sub1 returning_values o1;
	suspend;

	for select o1 from sub1 x into o1 do
		suspend;
end!

---

create function f1 returns integer
as
	declare procedure sub1 returns (o1 integer)
	as
	begin
		o1 = 1;
		suspend;
		o1 = 2;
		suspend;
		o1 = 3;
		suspend;
	end

	declare o1 integer = 0;
	declare v integer;
begin
	for select o1 from sub1 into v do
		o1 = o1 + v;

	return o1;
end!

select f1() from rdb$database!

---

execute block returns (o1 integer)
as
	declare procedure sub1 (i1 integer, i2 integer = 2) returns (o1 integer)
	as
	begin
		o1 = i2;
	end
begin
	execute procedure sub1 (0, 1) returning_values o1;
	suspend;

	execute procedure sub1 (0) returning_values o1;
	suspend;
end!

---

create procedure p2 (i1 integer) returns ("ó1" integer)
as
	declare procedure "súb1" (i1 integer) returns ("ó1" integer not null)
	as
	begin
		"ó1" = i1;
	end
begin
	execute procedure "súb1" (i1) returning_values "ó1";
end!

grant execute on procedure p2 to user qa_user2!

execute procedure p2 (1)!
execute procedure p2 (null)!

---

execute block returns (o1 integer)
as
	declare procedure sub1 (x integer) returns (x integer)
	as
	begin
	end
begin
end!

---

execute block returns (o1 integer)
as
	declare procedure sub1
	as
	begin
	end

	declare procedure sub1
	as
	begin
	end
begin
end!

---

execute block returns (o1 integer)
as
	declare procedure sub1
	as
		declare procedure sub11
		as
		begin
		end
	begin
	end
begin
end!

---

create domain d1 integer!
create domain d2 integer!
create domain d3 integer!

create table t1 (x1 d3)!

create procedure p3
as
	declare procedure sub1 returns (o1 d1)
	as
		declare x1 d2;
		declare x2 type of column t1.x1;
	begin
		execute procedure p1 returning_values o1;
		suspend;
	end

	declare v integer;
begin
	execute procedure sub1 returning_values v;
	select o1 from sub1 into v;
end!

commit!

select *
	from rdb$dependencies
	where rdb$dependent_name = 'P3'
	order by rdb$dependent_name, rdb$depended_on_name, rdb$field_name!

---

grant select on table t1 to user qa_user2!

create procedure p4
as
	declare procedure sub1
	as
	begin
		insert into t1 values (2);
	end
begin
	insert into t1 values (1);
	execute procedure sub1;
end!

grant all on table t1 to procedure p4!
grant execute on procedure p4 to user qa_user2!

create procedure p5
as
	declare procedure sub1
	as
	begin
		update t1 set x1 = x1 * 10;
	end
begin
	execute procedure sub1;
end!

grant execute on procedure p5 to user qa_user2!

commit!
set names utf8!
connect "WHERE_GDB:subproc.fdb" USER qa_user2 PASSWORD qa_user2!

execute procedure p4!
select * from t1 order by x1!

execute procedure p5!
select * from t1 order by x1!

execute block
as
	declare procedure sub1
	as
	begin
		update t1 set x1 = x1 * 10;
	end
begin
	execute procedure sub1;
end!

---

execute procedure p2 (1)!
execute procedure p2 (null)!

---

set blob all!
select rdb$procedure_blr from rdb$procedures where rdb$procedure_name = 'P1'!

---

execute block returns (i integer, o integer)
as
	-- Recursive procedure without forward declaration.
	declare procedure fibonacci(n integer) returns (o integer)
	as
		declare x integer;
	begin
		if (n = 0 or n = 1) then
			o = n;
		else
		begin
			execute procedure fibonacci(n - 1) returning_values x;
			execute procedure fibonacci(n - 2) returning_values o;
			o = o + x;
		end
	end
begin
	i = 0;

	while (i < 10)
	do
	begin
		execute procedure fibonacci(i) returning_values o;
		suspend;
		i = i + 1;
	end
end!

---

execute block returns (o integer)
as
	-- Forward declaration with default parameters.
	declare procedure p2(n integer = 20) returns (o integer);

	declare procedure p1(n integer = 10) returns (o integer)
	as
	begin
		o = (select o from p2) + (select o from p2(:n));
		suspend;
	end

	declare procedure p2(n integer) returns (o integer)
	as
	begin
		o = n;
		suspend;
	end

	-- Direct declaration with default parameters.
	declare procedure p3(n integer = 10) returns (o integer)
	as
	begin
		o = (select o from p2) + (select o from p2(:n));
		suspend;
	end
begin
	o = (select o from p1);
	suspend;

	o = (select o from p1(3));
	suspend;

	o = (select o from p2);
	suspend;

	o = (select o from p2(3));
	suspend;

	o = (select o from p3);
	suspend;

	o = (select o from p3(3));
	suspend;
end!

---

-- Error: duplicate procedure P1
execute block returns (o integer)
as
	declare procedure p1() returns (o integer);

	declare procedure p1() returns (o integer);

	declare procedure p1() returns (o integer)
	as
	begin
		o = 2;
		suspend;
	end
begin
	o = (select o from p1);
	suspend;
end!

---

-- Error: Sub-procedure P1 was declared but not implemented
execute block returns (o integer)
as
	declare procedure p1(n integer = 1) returns (o integer);

	declare procedure p2() returns (o integer)
	as
	begin
		o = 2;
		suspend;
	end
begin
	o = (select o from p2);
	suspend;

	-- Call a not-implemented procedure.
	o = (select o from p1);
	suspend;
end!

---

execute block returns (o integer)
as
	declare procedure p1(n integer = 1) returns (o integer);

	-- Error: Sub-procedure P1 has a signature mismatch with its forward declaration
	declare procedure p1() returns (o integer)
	as
	begin
		return 2;
	end
begin
	o = (select o from p1);
	suspend;
end!

---

execute block returns (o integer)
as
	declare procedure f1(n integer) returns (o integer);

	-- Error: Default values for parameters are not allowed in definition of the previously declared sub-procedure P1
	declare procedure f1(n integer = 1) returns (o integer)
	as
	begin
		return 2;
	end
begin
	o = (select o from p1);
	suspend;
end!

---

exit!

$ ISQL -q -m -e -i fb_sql_subproc_1.sql
$ DELETE fb_sql_subproc_1*
$ DROP WHERE_GDB:subproc.fdb
