
$ CREATE doc
By:          Clare Taylor
Date:        03/14/94
Test name:   IDML_C_SUBQ_06         
Series:      IDML_C_SUBQUERYS          
Results:     Uses a two-table join in the subquery to INSERT.
Dependency:  Requires tests.gdb database from IDML_C_SUBQ_02
History:
4/14/94:     Back to build P to add SET NAMES and chk results.

Description:
Inserts data into one test table and uses a subquery with a join 
from that table and the static data table to insert into a second 
test table.  Works and inserts the rows.

$ CREATE subq6.e
/*--------------------------------------------------------------------
  Case 5:  INSERT INTO <table>...SELECT ...WHERE a.field1=b.field1
----------------------------------------------------------------------*/
#include <WHERE_FILES:tcs.h>
EXEC SQL DATABASE db = "WHERE_GDB:tests.gdb";
EXEC SQL WHENEVER SQLERROR GOTO err;
EXEC SQL INCLUDE SQLCA;

static print_error()
{
    if (SQLCODE != 100)
        printf ("DATABASE ERROR, SQLCODE = %d \n", SQLCODE);
}
main()
{
     EXEC SQL SET NAMES DOS437;
     EXEC SQL CONNECT db;

     EXEC SQL DELETE FROM TEST_TABLE1;
     EXEC SQL DELETE FROM TEST_TABLE2;
     EXEC SQL COMMIT;
 
     EXEC SQL
         INSERT INTO TEST_TABLE1 (C_437_25)
	 SELECT C_437_25 FROM STRING_TABLE
		WHERE C_437_25 < 'Ålborg';
     EXEC SQL COMMIT;

     /* in other DB products, this would produce an 'ambiguous column'
	error since both string_table and test table use the same field names*/

     EXEC SQL
         INSERT INTO TEST_TABLE2 
         SELECT S_ROWID, C_ENUS, C_FRANCE, C_437_25 
	     FROM STRING_TABLE, TEST_TABLE1
             WHERE STRING_TABLE.C_437_25 = TEST_TABLE1.C_437_25;

     EXEC SQL COMMIT RELEASE;
     exit(0);
err: print_error();
}

$ CREATE ver6.sql 
SET NAMES DOS437;
connect "WHERE_GDB:tests.gdb";
SELECT C_437_25 FROM TEST_TABLE1;
SELECT C_437_25 FROM TEST_TABLE2;
quit;

$ CREATE subq6.sql 
SET NAMES DOS437;
connect "WHERE_GDB:tests.gdb";
delete from test_table1;
delete from test_table2;
commit;
select * from test_table1;
select * from test_table2;

INSERT INTO TEST_TABLE1 (C_437_25) 
    SELECT C_437_25 FROM STRING_TABLE 
       WHERE C_437_25 < 'Ålborg';

INSERT INTO TEST_TABLE2 
    SELECT S.S_ROWID, T.C_ENUS, T.C_FRANCE, T.C_437_25 FROM STRING_TABLE S, TEST_TABLE1 T
	WHERE S.C_437_25 = T.C_437_25;
commit;
select C_437_25 from test_table1;
select C_ENUS, C_FRANCE, C_437_25 from test_table2;

$ GPRE subq6.e
$ CC FLAG_CC subq6.c
$ LINK FLAG_LINK subq6 
$ RUN subq6
$ ISQL -i ver6.sql -m

$ ISQL -i subq6.sql -m
$ DELETE subq6* doc ver6.sql
