
>> er5.c
/*
 *	isc_dsql_exec_immed2
 *
 *	Pass an invalid database handle.
 *
 *  Test name: er5.c
 *  Created by: Marina Meyer
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"
int main()
{
	isc_db_handle	DB = 0;
	isc_tr_handle	trans = 0;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];
	char	*buf = "update x set y = 0";

	printf("Running ER4, invalid db handle\n");
	printf("to isc_exec_immed2\n");

	if ((rc=isc_attach_database(status, 0, "WHERE_GDB:somedb.gdb", &DB, 0, NULL)) !=0)
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_dsql_exec_immed2(status, &DB, &trans,0, buf, 1, 0, 0))==0)
		printf("BUG: exec_immed2 on invalid DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	DB = 0;
	if ((rc=isc_dsql_exec_immed2(status, &DB, &trans,0, buf, 1, 0, 0))==0)
		printf("BUG: exec_immed2 on Null DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	printf("Finished ER5\n");
}
$ CC FLAG_CC er5.c
$ LINK FLAG_LINK er5
$ RUN er5
$ DELETE er5*
