
$ CREATE er30.c
/*
 *	isc_dsql_prepare
 *
 *	Pass an invalid transaction handle.
 * 
 *  Test name: er30.c  
 *  Created by: Marina Meyer  
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"

int main()
{
	extern  char empdb[128];

	isc_db_handle	DB = NULL, DB2 = NULL;
	isc_tr_handle	trans = NULL;
        isc_stmt_handle	stmt = NULL;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];
	char	*s = "update department set budget = 0";

	printf("Running ER30, invalid transaction handle\n");
	printf("to isc_dsql_prepare\n");

	fill_db_parameter_buffer();

	if (isc_attach_database(status, 0, empdb, &DB, 0, 0L))
		{ERREXIT(status, rc, err_buf)};

	if ((rc=isc_dsql_allocate_statement(status, &DB, &stmt))!=0)
		{ERREXIT(status, rc, err_buf)};

	if ((rc=isc_start_transaction(status, &trans, 1, &DB2, 0, NULL))==0)
		printf("BUG: Bad DB to start trans.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_dsql_prepare(status, &trans, &stmt,0, s, 1, 0))==0)
		printf("BUG: Bad tr handle to prepare stmt.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	trans = NULL;
	if ((rc=isc_dsql_prepare(status, &trans, &stmt,0, s, 1, 0))==0)
		printf("BUG: Bad tr handle to prepare stmt.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_dsql_free_statement(status,&stmt, 2)) !=0)
		{ERREXIT(status, rc, err_buf)};

	if ((rc=isc_detach_database(status, &DB)) !=0)
		{ERREXIT(status, rc, err_buf)};

	printf("Finished ER30\n");
}
$ CC FLAG_CC er30.c
$ CC FLAG_CC globals.c
$ LINK FLAG_LINK er30 globals 
$ RUN er30
$ DELETE er30*
