
>> er12.c
/*
 *	isc_get_slice
 *
 *	Pass an invalid database handle.
 * 
 *  Test name: er12.c  
 *  Created by: Marina Meyer  
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"
int main()
{
	isc_db_handle	DB = NULL;
	isc_tr_handle	trans = NULL;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];

	short	sdl_length;
	long	len;
	int		cnt[4];
	char	sdl_buf[100];
	ISC_QUAD	array_id;

	printf("Running ER12, invalid db handle\n");
	printf("to isc_get_slice\n");

	if ((rc=isc_attach_database(status, 0, "WHERE_GDB:somedb.gdb", &DB, 0, NULL)) !=0)
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_get_slice(status, &DB, &trans,&array_id,sdl_length,
			sdl_buf, 0, 0, sizeof(cnt), cnt, &len))==0)
		printf("BUG: get slice on invalid DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	DB = NULL;
	if ((rc=isc_get_slice(status, &DB, &trans,&array_id,sdl_length,
			sdl_buf, 0, 0, sizeof(cnt), cnt, &len))==0)
		printf("BUG: get slice on Null DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	printf("Finished ER12\n");
}
$ CC FLAG_CC er12.c
$ LINK FLAG_LINK er12 
$ RUN er12
$ DELETE er12*
