
$ GBAK -r WHERE_FILES:employee.gbk WHERE_GDB:employee.gdb
$ CREATE globals.c
/*
**      Name:           globals.c
**      Programmer:     Ravil A. Desai
**      Description:    Declare and define global variables which will be
**                      used by OSRI test suites. There is a corresponding
**                      "globals.h" file, which need to be included in 
**                      test cases that uses the globals.
**
**      History:
**
**      Modified        04/15/1994      
**                             add interprete_stmt()
**      Modified        03/20/1994      
**                       add print_sqlda()
**                      add print_varfield()
**     Created         11/22/93
**
*/
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#undef _Windows

typedef struct vary512 {
	short vary_length;
	char vary_string[513];
	} VARY512;

#ifndef _Windows
#ifndef DARWIN
#include <ibase.h>
#else
#include <Firebird/ibase.h>
#endif
#define LogPrintf printf
void print_varfield();
void print_sqlda();
void fill_db_parameter_buffer();
void osri_print_status();
void interprete_stmt_info();
#else
#include "globals.h"
void print_varfield(VARY512*);
void print_sqlda(XSQLDA ISC_FAR*);
void fill_db_parameter_buffer(void);
void osri_print_status(char*, ISC_STATUS*);
void interprete_stmt_info(isc_stmt_handle, char*);
#endif

char   db_param[255];
char   *pdb_param = db_param;
char   *p;
int    len;

char	atlas1[128];
char	atlas2[128];
char	foo_db[128];
char	empdb[128];

static char     count_info [] = { isc_info_sql_records };
 

#ifdef _Windows
void fill_db_parameter_buffer(void)
#else
void fill_db_parameter_buffer()
#endif
{

#ifdef _Windows
   strcpy(empdb,"WHERE_GDB:employee.gdb");
#else
   strcpy(empdb,"WHERE_GDB:employee.gdb");
#endif
}


#ifdef _Windows
void osri_print_status(char *msg_string, ISC_STATUS *status)
#else
void osri_print_status(msg_string, status)
char  *msg_string; 
ISC_STATUS *status;
#endif
{

  int   i, j;
  int   status_size = 20;
  char  output_str[255];
  char  *p;

  LogPrintf("%s\n", msg_string);
  LogPrintf("*** Status Vector ****\n");

  for (i = 0; i < status_size; ) {
	 for (j = 0, p = output_str;
			(j < 5 && i < status_size);
			j++, p += strlen(p), i++)
		sprintf(p, "[%2d]: %ld ", i, status[i]);
	 LogPrintf("%s\n", output_str);
  }

  LogPrintf("%s, sqlcode = %d\n", msg_string, isc_sqlcode(status));
  isc_print_status(status);
  isc_print_sqlerror (isc_sqlcode(status), status); 
}


/*-----------------------------------------------------------------
**      Need more work on how to examine DATE, ARRAY, BLOB fields.
**-----------------------------------------------------------------
*/

#ifdef _Windows
void print_sqlda(XSQLDA ISC_FAR *sqlda)
#else
void print_sqlda(sqlda)
XSQLDA ISC_FAR *sqlda;
#endif
{
	short i;

	LogPrintf("******* SQLDA *******\n");
	LogPrintf("Version: %d, NameField: %s, ByteCount: %d\n",
		sqlda->version, sqlda->sqldaid, sqlda->sqldabc);
	LogPrintf("No.Fields alloc: %d, Actual No.Fields: %d\n",
		sqlda->sqln, sqlda->sqld);
	for (i = 0; i < sqlda->sqld; i++) {
	    LogPrintf("Field Number :%d\tLength: %d\tType: ", i+1,
		 sqlda->sqlvar[i].sqllen);
	    switch (sqlda->sqlvar[i].sqltype) {
		case SQL_TEXT+1:
			LogPrintf("TEXT\n");
			LogPrintf("Data:%s\n",(char *)(sqlda->sqlvar[i].sqldata));
			break;
		case SQL_VARYING+1:
			LogPrintf("VARYING\n");
			print_varfield((VARY512 *)((char *)(sqlda->sqlvar[i].sqldata))); 
			LogPrintf("\n");
			break;
		case SQL_SHORT+1:
			LogPrintf("SHORT\n");
			LogPrintf("Data:%d\n",*((short *)(sqlda->sqlvar[i].sqldata)));
			break;
		case SQL_LONG+1:
			LogPrintf("LONG\n");
			LogPrintf("Data:%d\n",*((long *)(sqlda->sqlvar[i].sqldata)));
			break;
		case SQL_FLOAT+1:
			LogPrintf("FLOAT\n");
			LogPrintf("Data:%f\n",*((float *)(sqlda->sqlvar[i].sqldata)));
			break;
		case SQL_DOUBLE+1:
			LogPrintf("DOUBLE\n");
			LogPrintf("Data:%f\n",*((double *)(sqlda->sqlvar[i].sqldata)));
			break;
		case SQL_D_FLOAT+1:
			LogPrintf("D_FLOAT\n");
			LogPrintf("Data:%f\n",*((double *)(sqlda->sqlvar[i].sqldata)));
			break;
		case SQL_DATE+1:
			LogPrintf("DATE\n");
			LogPrintf("Data Address:%s\n",sqlda->sqlvar[i].sqldata);
			break;
		case SQL_BLOB+1:
			LogPrintf("BLOB\n");
			LogPrintf("Data Address:%s\n",sqlda->sqlvar[i].sqldata);
			break;
		case SQL_ARRAY+1:
			LogPrintf("ARRAY\n");
			LogPrintf("Data Address:%s\n",sqlda->sqlvar[i].sqldata);
			break;
		default:
			LogPrintf("Unkowned\n");
			LogPrintf("Data Address:%s\n",sqlda->sqlvar[i].sqldata);
	    }
	    LogPrintf("\tScale: %d\tSubType: %d\n",sqlda->sqlvar[i].sqlscale, 
			sqlda->sqlvar[i].sqlsubtype);

	    LogPrintf("Indicator: %d\tColName Len: %d\tColName: %s\n",
			*((short *)(sqlda->sqlvar[i].sqlind)), sqlda->sqlvar[i].sqlname_length,
			sqlda->sqlvar[i].sqlname);
	    LogPrintf("RelName Len: %d\tRelName: %s\n",
			sqlda->sqlvar[i].relname_length, sqlda->sqlvar[i].relname);

	    LogPrintf("OwnName Len: %d\tOwnName: %s\n",
			sqlda->sqlvar[i].ownname_length, sqlda->sqlvar[i].ownname);

	    LogPrintf("AliaseName Len: %d\tAliaseName: %s\n",
			sqlda->sqlvar[i].aliasname_length, sqlda->sqlvar[i].aliasname);
	}
}


#ifdef _Windows
void print_varfield(VARY512 *varfield)
#else
void print_varfield(varfield)
VARY512 *varfield;
#endif
{
	if (!varfield)
		return;
	varfield->vary_string[varfield->vary_length] = '\0';    
	LogPrintf("%s", varfield->vary_string);
}



#ifdef _Windows
void interprete_stmt_info(isc_stmt_handle stmt, char *info_buffer)
#else
void interprete_stmt_info(stmt, info_buffer)
isc_stmt_handle stmt;
char *info_buffer;
#endif
{
	char count_type, count_is, *p;
	char  count_buffer[33];

	long l, count;
	long statement_type;
	ISC_STATUS status[20];
 
	count_type = 0;
	count = 0;
 

	if (info_buffer [0] == isc_info_sql_stmt_type)
	{
		l = isc_vax_integer (info_buffer + 1, 2);
		statement_type = isc_vax_integer (info_buffer + 3, l);
	}

	if (statement_type == isc_info_sql_stmt_update)
		count_type = isc_info_req_update_count;
	
	if (statement_type == isc_info_sql_stmt_delete)
		count_type = isc_info_req_delete_count;
 
	if (statement_type == isc_info_sql_stmt_select)
		count_type = isc_info_req_select_count;
 
	if (statement_type == isc_info_sql_stmt_insert)
		count_type = isc_info_req_insert_count;
 
	/* Only get counts for known statement types */
	if (count_type)
	{
		isc_dsql_sql_info (status, &stmt, sizeof (count_info),
		count_info, sizeof (count_buffer), count_buffer);

		for (p = count_buffer + 3; *p != isc_info_end; )
		{
			count_is = *p++;
			l = isc_vax_integer (p, 2);
			p += 2;
			count = isc_vax_integer (p, l);
			p += l;
			/* This is the matching count type */
			if (count_is == count_type)
			break;
		}

		/* we assume that we did get a match */
		LogPrintf ( "Rows affected:  %d\n", count);
	}
	return;
}

$ CC FLAG_CC globals.c
