
$ CREATE er40.c
/*
 *	isc_put_slice
 *
 *	Pass an invalid transaction handle.
 * 
 *  Test name: er40.c  
 *  Created by: Marina Meyer  
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"

int main()
{
	extern  char empdb[128];

	isc_db_handle	DB = NULL, DB2 = NULL;
	isc_tr_handle	trans = NULL;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];
	ISC_ARRAY_DESC	desc;
	long	len;
	int		cnt[4];
	ISC_QUAD	array_id;
	short	sdl_length;
	char	sdl_buf[100];

	printf("Running ER40, invalid transaction handle\n");
	printf("to isc_put_slice\n");

	fill_db_parameter_buffer();

	if (isc_attach_database(status, 0, empdb, &DB, 0, 0L))
		{ERREXIT(status, rc, err_buf)};

	if ((rc=isc_start_transaction(status, &trans, 1, &DB2, 0, NULL))==0)
		printf("BUG: Bad DB to start trans.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_put_slice(status, &DB, &trans, &array_id,
			sdl_length, sdl_buf, 0, 0L, sizeof(cnt), cnt))==0)
		printf("BUG: Bad tr handle to put slice.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	trans = NULL;
	if ((rc=isc_put_slice(status, &DB, &trans, &array_id,
			sdl_length, sdl_buf, 0, 0L, sizeof(cnt), cnt))==0)
		printf("BUG: Bad tr handle to put slice.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_detach_database(status, &DB)) !=0)
		{ERREXIT(status, rc, err_buf)};

	printf("Finished ER40\n");
}
$ CC FLAG_CC er40.c
$ CC FLAG_CC globals.c
$ LINK FLAG_LINK er40 globals 
$ RUN er40
$ DELETE er40*
