
>> er3.c
/*
 *	isc_dsql_alloc_statement2
 *
 *	Pass an invalid database handle.
 *
 *  Test name: er3.c
 *  Created by: Marina Meyer
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"
int main()
{
	isc_db_handle	DB = 0;
	isc_stmt_handle	stmt = 0;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];

	printf("Running ER3, invalid db handle to alloc_stmt2\n");

	if ((rc=isc_attach_database(status, 0, "WHERE_GDB:somedb.gdb", &DB, 0, NULL)) !=0)
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_dsql_alloc_statement2(status, &DB, &stmt)) ==0)
		printf("BUG: invalid DB on alloc stmt.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	DB = 0;
	if ((rc=isc_dsql_alloc_statement2(status, &DB, &stmt)) ==0)
		printf("BUG: Null DB on alloc stmt.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	printf("Finished ER3\n");
}
$ CC FLAG_CC er3.c
$ LINK FLAG_LINK er3
$ RUN er3
$ DELETE er3*
