
$ CREATE er15.c
/*
 *	isc_array_put_slice
 *
 *	Pass an invalid database handle.
 * 
 *  Test name: er15.c  
 *  Created by: Marina Meyer  
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"
int main()
{
	isc_db_handle	DB = NULL;
	isc_tr_handle	trans = NULL;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];

	short	sdl_length;
	long	len;
	int		cnt[4];
	char	sdl_buf[100];
	ISC_QUAD	array_id;
	ISC_ARRAY_DESC  desc;
	short	length,dim;
	short	kludge = SQL_SHORT;

	LogPrintf("Running ER15, array put slice on invalid DB.\n");

	if ((rc=isc_attach_database(status, 0, "WHERE_GDB:somedb.gdb", &DB, 0, NULL)) !=0)
		{ERRCONTINUE(status, rc, err_buf)};

	length=4;
	dim=1;
/*
	isc_array_set_desc(status,"PROF_DEPT_BUDGET","QUART_HEAD_CNT","SQL_SHORT",&length,&dim,&desc);
*/
	isc_array_set_desc(status,"PROF_DEPT_BUDGET","QUART_HEAD_CNT",
		&kludge,&length,&dim,&desc);

	if ((rc=isc_array_put_slice(status, &DB, &trans,
			&array_id, &desc, cnt, &len)) ==0)
		LogPrintf("BUG: array put slice on invalid DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	DB = NULL;
	if ((rc=isc_array_put_slice(status, &DB, &trans,
			&array_id, &desc, cnt, &len)) ==0)
		LogPrintf("BUG: array put slice on Null DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	LogPrintf("Finished ER15\n");
}
$ CC FLAG_CC er15.c
$ LINK FLAG_LINK er15 
$ RUN er15
$ DELETE er15*
