
>> er34.c
/*
 *	isc_open_blob2
 *
 *	Pass an invalid transaction handle.
 *
 *  Test name: er34.c
 *  Created by: Marina Meyer
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"

int main()
{
	extern  char empdb[128];

	isc_db_handle	DB = 0, DB2 = 0;
	isc_tr_handle	trans = 0;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];
	ISC_QUAD	blob_id;
        isc_blob_handle blob_handle=0;
	int		len;
	char		bpb[32];

	printf("Running ER34, invalid transaction handle\n");
	printf("to isc_open_blob2\n");

	fill_db_parameter_buffer();

	if (isc_attach_database(status, 0, empdb, &DB, 0, 0L))
		{ERREXIT(status, rc, err_buf)};

	if ((rc=isc_start_transaction(status, &trans, 1, &DB2, 0, NULL))==0)
		printf("BUG: Bad DB to start trans.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_open_blob2(status, &DB, &trans,&blob_handle, &blob_id,
			len, bpb)) ==0)
		printf("BUG: Bad tr handle to open blob2.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	trans = 0;
	if ((rc=isc_open_blob2(status, &DB, &trans,&blob_handle, &blob_id,
			len, bpb)) ==0)
		printf("BUG: Bad tr handle to open blob2.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_detach_database(status, &DB)) !=0)
		{ERREXIT(status, rc, err_buf)};

	printf("Finished ER34\n");
}
$ CC FLAG_CC er34.c
$ CC FLAG_CC globals.c
$ LINK FLAG_LINK er34 globals
$ RUN er34
$ DELETE er34*
