
$ CREATE er7.c
/*
 *	isc_create_blob2
 *
 *	Pass an invalid database handle.
 * 
 *  Test name: er7.c  
 *  Created by: Marina Meyer  
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"
int main()
{
	isc_db_handle	DB = NULL;
	isc_tr_handle	trans = NULL;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];
	ISC_QUAD	blob_id;
	isc_blob_handle	blob_handle = NULL;
	int		len;
	char		bpb[32];

	printf("Running ER7, invalid db handle\n");
	printf("to isc_create_blob2\n");

	if ((rc=isc_attach_database(status, 0, "WHERE_GDB:somedb.gdb", &DB, 0, NULL)) !=0)
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_create_blob2(status, &DB, &trans,
			&blob_handle, &blob_id, len, bpb)) ==0)
		printf("BUG: create blob2 on invalid DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	DB = NULL;
	if ((rc=isc_create_blob2(status, &DB, &trans,
			&blob_handle, &blob_id, len, bpb)) ==0)
		printf("BUG: create blob2 on Null DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	printf("Finished ER7\n");
}
$ CC FLAG_CC er7.c
$ LINK FLAG_LINK er7 
$ RUN er7
$ DELETE er7*
