
$ CREATE er22.c
/*
 *	isc_cancel_events
 *
 *	Pass an invalid database handle.
 * 
 *  Test name: er22.c  
 *  Created by: Marina Meyer  
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"

int main()
{
	isc_db_handle	DB = NULL;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];
	long	event_id;

	printf("Running ER22, invalid db handle\n");
	printf("to isc_cancel_events\n");

	if ((rc=isc_attach_database(status, 0, "WHERE_GDB:somedb.gdb", &DB, 0, NULL)) !=0)
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_cancel_events(status, &DB, &event_id))==0)
		printf("BUG: Bad DB to cancal event\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	DB = NULL;
	if ((rc=isc_cancel_events(status, &DB, &event_id))==0)
		printf("BUG: Bad DB to cancal event\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	printf("Finished ER22\n");
}
$ CC FLAG_CC er22.c
$ LINK FLAG_LINK er22 
$ RUN er22
$ DELETE er22*
