
>> er25.c
/*
 *	isc_dsql_execute_immediate
 *
 *	Pass an invalid transaction handle.
 *
 *  Test name: er25.c
 *  Created by: Marina Meyer
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"

int main()
{
	extern  char empdb[128];

	char 	*s = "insert into country values ('y', 'y')";
	isc_db_handle	DB = 0, DB2 = 0;
	isc_tr_handle	trans = 0;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];

	printf("Running ER25, Bad tr handle to exec immed.\n");

	fill_db_parameter_buffer();

	if (isc_attach_database(status, 0, empdb, &DB, 0, 0L))
		{ERREXIT(status, rc, err_buf)};

	if ((rc=isc_start_transaction(status, &trans, 1, &DB2, 0, NULL))==0)
		printf("BUG: Bad DB to start trans.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_dsql_execute_immediate(status, &DB, &trans, 0, s, 1, 0))==0)
		printf("BUG: Bad tr to exec immed.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	trans = 0;
	if ((rc=isc_dsql_execute_immediate(status, &DB, &trans, 0, s, 1, 0))==0)
		printf("BUG: Bad tr to exec immed.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	if (isc_detach_database(status, &DB))
		{ERREXIT(status, rc, err_buf)};

	printf("Finished ER25\n");
}
$ CC FLAG_CC er25.c
$ CC FLAG_CC globals.c
$ LINK FLAG_LINK er25 globals
$ RUN er25
$ DELETE er25*
