
>> er26.c
/*
 *	isc_dsql_execute
 *
 *	Pass an invalid transaction handle.
 *
 *  Test name: er26.c
 *  Created by: Marina Meyer
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"

int main()
{
	extern  char empdb[128];

	char 	*s = "update department set budget = 0";
	isc_db_handle	DB = 0, DB2 = 0;
	isc_tr_handle	trans = 0;
        isc_stmt_handle	stmt = 0;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];

	printf("Running ER26, invalid transaction handle\n");
	printf("to isc_dsql_execute\n");

	fill_db_parameter_buffer();

	if ((rc=isc_attach_database(status, 0, empdb, &DB, 0, 0L)) !=0)
		{ERREXIT(status, rc, err_buf)};

	if ((rc=isc_dsql_allocate_statement(status, &DB, &stmt)) !=0)
		{ERREXIT(status, rc, err_buf)};

	if ((rc=isc_start_transaction(status, &trans, 1, &DB, 0, NULL))!=0)
		{ERREXIT(status, rc, err_buf)};

	if ((rc=isc_dsql_prepare(status, &trans, &stmt,0, s, 1, 0)) !=0)
		{ERREXIT(status, rc, err_buf)};

	if ((rc=isc_commit_transaction (status, &trans)) !=0)
		{ERREXIT(status, rc, err_buf)};

	if ((rc=isc_start_transaction(status, &trans, 1,&DB2, 0, NULL))==0)
		printf("BUG: Bad DB to start trans.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_dsql_execute(status, &trans, &stmt, 1, 0L)) ==0)
		printf("BUG: Bad tr handle to dsql execute.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	trans = 0;
	if ((rc=isc_dsql_execute(status, &trans, &stmt, 1, 0L)) ==0)
		printf("BUG: Bad tr handle to dsql execute.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_dsql_free_statement(status,&stmt, 2)) !=0)
		{ERREXIT(status, rc, err_buf)};

	if ((rc=isc_detach_database(status, &DB)) !=0)
		{ERREXIT(status, rc, err_buf)};

	printf("Finished ER26\n");
}
$ CC FLAG_CC er26.c
$ CC FLAG_CC globals.c
$ LINK FLAG_LINK er26 globals
$ RUN er26
$ DELETE er26*
