
$ CREATE er6.c
/*
 *	isc_create_blob
 *
 *	Pass an invalid database handle.
 * 
 *  Test name: er6.c  
 *  Created by: Marina Meyer  
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"
int main()
{
	isc_db_handle	DB = NULL;
	isc_tr_handle	trans = NULL;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];
	ISC_QUAD	blob_id;
	isc_blob_handle	blob_handle = NULL;

	printf("Running ER6, invalid db handle\n");
	printf("to isc_create_blob\n");


	if ((rc=isc_attach_database(status, 0, "WHERE_GDB:somedb.gdb", &DB, 0, NULL)) !=0)
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_create_blob(status, &DB, &trans,&blob_handle, &blob_id))==0)
		printf("BUG: create blob on invalid DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	DB = NULL;
	if ((rc=isc_create_blob(status, &DB, &trans,&blob_handle, &blob_id))==0)
		printf("BUG: create blob on Null DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	printf("Finished ER6\n");
}
$ CC FLAG_CC er6.c
$ LINK FLAG_LINK er6 
$ RUN er6
$ DELETE er6*
