
>> er28.c
/*
 *	isc_dsql_execute_immediate
 *
 *	Pass an invalid transaction handle.
 *
 *  Test name: er28.c
 *  Created by: Marina Meyer
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"

int main()
{
	extern  char empdb[128];

	char *s = "insert into country values ('y', 'y')";

	isc_db_handle	DB = 0, DB2 = 0;
	isc_tr_handle	trans = 0;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];

	printf("Running ER28, invalid transaction handle\n");
	printf("to isc_dsql_execute_immediate\n");

	fill_db_parameter_buffer();

	if (isc_attach_database(status, 0, empdb, &DB, 0, 0L))
		{ERREXIT(status, rc, err_buf)};

	if ((rc=isc_start_transaction(status, &trans, 1, &DB2, 0, NULL))==0)
		printf("BUG: Bad DB to start trans.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_dsql_execute_immediate(status, &DB, &trans,0, s, 1, 0))==0)
		printf("BUG: Bad tr handle to exec immed.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	trans = 0;
	if ((rc=isc_dsql_execute_immediate(status, &DB, &trans,0, s, 1, 0))==0)
		printf("BUG: Bad tr handle to exec immed.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_detach_database(status, &DB)) !=0)
		{ERREXIT(status, rc, err_buf)};

	printf("Finished ER28\n");
}
$ CC FLAG_CC er28.c
$ CC FLAG_CC globals.c
$ LINK FLAG_LINK er28 globals
$ RUN er28
$ DELETE er28*
