
>> er11.c
/*
 *	isc_array_lookup_desc
 *
 *	Pass an invalid database handle.
 *
 *  Test name: er11.c
 *  Created by: Marina Meyer
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"
int main()
{
	isc_db_handle	DB = 0;
	isc_tr_handle	trans = 0;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];
	ISC_ARRAY_DESC	desc;

	printf("Running ER11, invalid db handle\n");
	printf("to array_lookup_desc\n");

	if ((rc=isc_attach_database(status, 0, "WHERE_GDB:somedb.gdb", &DB, 0, NULL)) !=0)
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_array_lookup_desc(status, &DB, &trans,
			"JOB", "JOB_REQUIREMENT", &desc)) ==0)
		printf("BUG: array lookup desc on invalid DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	DB = 0;
	if ((rc=isc_array_lookup_desc(status, &DB, &trans,
			"JOB", "JOB_REQUIREMENT", &desc)) ==0)
		printf("BUG: array lookup desc on Null DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	printf("Finished ER11\n");
}
$ CC FLAG_CC er11.c
$ LINK FLAG_LINK er11
$ RUN er11
$ DELETE er11*
