
>> er19.c
/*
 *	isc_dsql_finish
 *
 *	Pass an invalid database handle.
 *	No error expected.
 *
 *  Test name: er19.c
 *  Created by: Marina Meyer
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"
int main()
{
	isc_db_handle	DB = 0;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];

	printf("Running ER19, dsql finish on invalid DB.\n");

	if ((rc=isc_attach_database(status, 0, "WHERE_GDB:somedb.gdb", &DB, 0, NULL)) !=0)
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_dsql_finish(&DB)) ==0)
		printf("BUG: dsql finish on invalid DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	DB = 0;
	if ((rc=isc_dsql_finish(&DB)) ==0)
		printf("BUG: dsql finish on Null DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	printf("Finished ER19\n");
}
$ CC FLAG_CC er19.c
$ LINK FLAG_LINK er19
$ RUN er19
$ DELETE er19*
