
$ CREATE er17.c
/*
 *	isc_database_info
 *
 *	Pass an invalid database handle.
 * 
 *  Test name: er17.c  
 *  Created by: Marina Meyer  
 *  Date created: April 1994
 */

#include "WHERE_FILES:isc_test.h"

static char ilist[] = {isc_info_page_size};

int main()
{
	isc_db_handle	DB = NULL;
	ISC_STATUS 	rc, status[20];
	char		err_buf[128];

	char	info_buf[32];

	printf("Running ER17, db info on invalid DB.\n");
	printf("to isc_database_info\n");

	if ((rc=isc_attach_database(status, 0, "WHERE_GDB:somedb.gdb", &DB, 0, NULL)) !=0)
		{ERRCONTINUE(status, rc, err_buf)};

	if ((rc=isc_database_info(status, &DB, sizeof(ilist), ilist,
			sizeof(info_buf), info_buf)) ==0)
		printf("BUG: database info on invalid DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	DB = NULL;
	if ((rc=isc_database_info(status, &DB, sizeof(ilist), ilist,
			sizeof(info_buf), info_buf)) ==0)
		printf("BUG: database info on Null DB.\n");
        else
		{ERRCONTINUE(status, rc, err_buf)};

	printf("Finished ER17\n");
}
$ CC FLAG_CC er17.c
$ LINK FLAG_LINK er17 
$ RUN er17
$ DELETE er17*
