
$GBAK -r sp1.gbk WHERE_GDB:sp1.gdb
$ ISQL -sqldialect 3 WHERE_GDB:sp1.gdb
set term go;
create procedure cast1(a numeric(5,2)) RETURNS (b smallint) as
begin
    b = a/2;
    SUSPEND;
end
go
create procedure cast2(a numeric(5,2)) RETURNS (b integer) as
begin
    b = a * 100;
    SUSPEND;
end
go
create procedure cast3(a numeric(5,2)) RETURNS (b float) as
begin
    b = a * 100;
    SUSPEND;
end
go
create procedure cast4(a numeric(5,2)) RETURNS (b double precision) as
begin
    b = a * 100;
    SUSPEND;
end
go
create procedure cast5(a numeric(5,2)) RETURNS (b decimal(5,2)) as
begin
    b = a * 100;
    SUSPEND;
end
go
create procedure cast6(a numeric(5,2)) RETURNS (b date) as
begin
    b = a;
    SUSPEND;
end
go
create procedure cast7(a numeric(5,2)) RETURNS (b numeric(5,2)) as
begin
    b = a;
    SUSPEND;
end
go
create procedure cast8(a numeric(5,2) ) RETURNS (b blob) as begin
   b = a;
   SUSPEND;
 end
go
create procedure cast9(a numeric(5,2)) RETURNS (b char(10)) as 
begin 
    b = a; 
    SUSPEND; 
end 
go 
create procedure cast10(a numeric(5,2)) RETURNS (b varchar(10)) as 
 begin
   b = a; 
   SUSPEND; 
 end 
go 

commit
go
set term ; go
execute procedure cast1 100.99;
execute procedure cast2 100.99;
execute procedure cast3 100.99;
execute procedure cast4 100.99;
execute procedure cast5 100.99;
execute procedure cast6 100.99;
execute procedure cast7 100.99;
execute procedure cast9 100.99;
execute procedure cast10 100.99;

exit;
$ DROP WHERE_GDB:sp1.gdb
