
>> proc_level0_tests1.sql
/* This script checks wheather procedure names are case sensitive or not.*/
create database "WHERE_GDB:foo.gdb";
set echo;
set term go;
create procedure abc RETURNS( x varchar(2)) as
begin
  x = 'Q';
  SUSPEND;
end
go
create procedure ABC RETURNS( x varchar(2)) as
begin
  x = 'Q';
  SUSPEND;
end
go

set term ; go
show proc;

$ISQL -m -i proc_level0_tests1.sql
$DROP WHERE_GDB:foo.gdb
$DELETE proc_level0_tests1*
