
$ GBAK -r sp1.gbk WHERE_GDB:sp1.gdb
$ ISQL -m WHERE_GDB:sp1.gdb
set term go;
create procedure proc13 RETURNS (a varchar(5), b varchar(21), c integer) as
begin
    for select p.pno,pname, count(*) from p, sp where p.pno = sp.pno group by p.pno, pname
    into :a, :b, :c
    do SUSPEND;
end
go
set term ; go
EXECUTE PROCEDURE PROC13 ;
SELECT  * FROM PROC13;
SELECT MAX(A) FROM PROC13;
SELECT  C FROM PROC13;
SELECT C,A FROM PROC13 ORDER BY C;
SELECT A, AVG(C) FROM PROC13 GROUP BY A HAVING AVG(C) > 1;
SELECT A, AVG(C) FROM PROC13 GROUP BY A ;
SELECT A , C FROM PROC13
        WHERE C > (SELECT AVG(C) FROM PROC13);
exit;
$ DROP WHERE_GDB:sp1.gdb 
