
$ ISQL -m 
create database "WHERE_GDB:foo.gdb";
set term go;
create procedure proc RETURNS (abcdefghijklmnopqrstuvwxyzabcde  int) as
begin
   abcdefghijklmnopqrstuvwxyzabcde = 10;
   SUSPEND;
end
go

create procedure proc1 RETURNS (abcdefghijklmnopqrstuvwxyzabcdef  int) as
begin
   abcdefghijklmnopqrstuvwxyzabcdef = 10;
   SUSPEND;
end
go


set term ; go
show procedures;
exit;
$ DROP WHERE_GDB:foo.gdb
