
$GBAK -r sp1.gbk WHERE_GDB:sp1.gdb
$ ISQL -sqldialect 3 WHERE_GDB:sp1.gdb
set term go;
create procedure cast1(a float) RETURNS (b smallint) as
begin
    b = a/2;
    SUSPEND;
end
go
create procedure cast2(a float) RETURNS (b integer) as
begin
    b = a * 100;
    SUSPEND;
end
go
create procedure cast3(a float) RETURNS (b float) as
begin
    b = a * 100;
    SUSPEND;
end
go
create procedure cast4(a float) RETURNS (b double precision) as
begin
    b = a * 100;
    SUSPEND;
end
go
create procedure cast5(a float) RETURNS (b decimal(5,2)) as
begin
    b = a * 100;
    SUSPEND;
end
go
create procedure cast6(a float) RETURNS (b date) as
begin
    b = a;
    SUSPEND;
end
go
create procedure cast7(a float) RETURNS (b numeric(5,2)) as
begin
    b = a;
    SUSPEND;
end
go
create procedure cast8(a float ) RETURNS (b blob) as begin
   b = a;
   SUSPEND;
 end
go
create procedure cast9(a float) RETURNS (b char(10)) as
begin
    b = a;
    SUSPEND;
end
go
create procedure cast10(a float ) RETURNS (b varchar(10)) as
 begin
   b = a;
   SUSPEND;
 end
go

commit
go
set term ; go
execute procedure cast1 100.00;
execute procedure cast2 100.00;
execute procedure cast3 100.00;
execute procedure cast4 100.00;
execute procedure cast5 100.00;
execute procedure cast6 100.00;
execute procedure cast7 100.00;
execute procedure cast9 100.00;
execute procedure cast10 100.00;
exit;
$ DROP WHERE_GDB:sp1.gdb
