
$ GBAK -r sp1.gbk WHERE_GDB:sp1.gdb

>> proc_isql_19.sql
set term go;
create procedure  proc_select_insert2 as
declare variable t varchar(5); 
begin
    for select sno from s where sno NOT IN
    (select sno from sp) into :t do
    begin
      insert into sp(sno) values (:t);
    end
end
go
set term ; go
set echo;
select * from sp;
EXECUTE PROCEDURE PROC_SELECT_INSERT2;
select * from sp;
exit;

$ ISQL -m WHERE_GDB:sp1.gdb -i proc_isql_19.sql
$ DROP WHERE_GDB:sp1.gdb 
$DELETE proc_isql_19*
