
/**************************************************************
* Name: Sudhanshu Kumar
* Purpose: Can not use select * from p1 where p1 is proc
*          inside another proc p2. You can not even make 
*          a procedure.
**************************************************************/ 
$ GBAK -r sp1.gbk WHERE_GDB:sp1.gdb
$ ISQL WHERE_GDB:sp1.gdb
create table t (x int);
insert into t values(1);
insert into t values(2);
set term go;   
 create procedure p1 as
  begin
     insert into t values(3);
  end 
 go 
 create procedure p2 as  
   begin  
     select * from p1;  
   end  
go  
set term ; go 
execute procedure p1;
select * from t;
exit; 
$ DROP WHERE_GDB:sp1.gdb
