
$GBAK -r sp1.gbk WHERE_GDB:sp1.gdb

>> proc_cast9.sql
set term go;
create procedure cast1(a char(10)) RETURNS (b smallint) as
begin
    b = a/2;
    SUSPEND;
end
go
create procedure cast2(a char(10)) RETURNS (b integer) as
begin
    b = a * 100;
    SUSPEND;
end
go
create procedure cast3(a char(10)) RETURNS (b float) as
begin
    b = a * 100;
    SUSPEND;
end
go
create procedure cast4(a char(10)) RETURNS (b double precision) as
begin
    b = a * 100;
    SUSPEND;
end
go
create procedure cast5(a char(10)) RETURNS (b decimal(5,2)) as
begin
    b = a * 100;
    SUSPEND;
end
go
create procedure cast6(a char(10)) RETURNS (b date) as
begin
    b = a;
    SUSPEND;
end
go
create procedure cast7(a char(10)) RETURNS (b numeric(5,2)) as
begin
    b = a;
    SUSPEND;
end
go
create procedure cast8(a char(10) ) RETURNS (b blob) as begin
   b = a;
   SUSPEND;
 end
go
create procedure cast9(a char(10)) RETURNS (b char(10)) as
begin
    b = a;
    SUSPEND;
end
go
create procedure cast10(a char(10) ) RETURNS (b varchar(10)) as begin
   b = a;
   SUSPEND;
 end
go

commit
go
set term ; go
execute procedure cast1 '100';
execute procedure cast1 'abc';
execute procedure cast2 '100';
execute procedure cast2 'abc';
execute procedure cast3 '100';
execute procedure cast3 'abc';
execute procedure cast4 '100';
execute procedure cast4 'abc';
execute procedure cast5 '100';
execute procedure cast5 'abc';
execute procedure cast6 '12-Mar-92';
execute procedure cast6 'abc';
execute procedure cast6 abc;
execute procedure cast6 100;
execute procedure cast7 '100';
execute procedure cast7 'abc';
execute procedure cast9 '100';
execute procedure cast9 'abc';
execute procedure cast10 '100';
execute procedure cast10 'abc';
exit;

$ ISQL -m -sqldialect 3 WHERE_GDB:sp1.gdb -i proc_cast9.sql
$ DROP WHERE_GDB:sp1.gdb
$DELETE proc_cast9*
