
>> proc_level_tests_2.sql

create database "WHERE_GDB:foo.gdb";
set term go;
create procedure proc RETURNS (abcdefghijklmnopqrstuvwxyzabcde  int) as
begin
   abcdefghijklmnopqrstuvwxyzabcde = 10;
   SUSPEND;
end
go

create procedure proc1 RETURNS (abcdefghijklmnopqrstuvwxyzabcdef  int) as
begin
   abcdefghijklmnopqrstuvwxyzabcdef = 10;
   SUSPEND;
end
go


set term ; go
show procedures;
exit;

$ISQL -m -i proc_level_tests_2.sql
$DROP WHERE_GDB:foo.gdb
$DELETE proc_level_tests_2*
