
$ GBAK -r sp1.gbk WHERE_GDB:sp1.gdb
$ ISQL WHERE_GDB:sp1.gdb
set term go;
create procedure proc2  RETURNS (a varchar(5), b varchar(5),c integer) as
begin
   select *  from sp where pno = 'P5'
     into :a, :b, :c;
   SUSPEND;
end
go
set term ; go
EXECUTE PROCEDURE PROC2;
SELECT  * FROM PROC2;
SELECT  MAX(C) FROM PROC2;
SELECT  A FROM PROC2;
SELECT  * FROM PROC2 ORDER BY C;
SELECT A, AVG(C) FROM PROC2 GROUP BY A HAVING AVG(C) > 350;
SELECT A, AVG(C) FROM PROC2 GROUP BY A ;
SELECT A, C FROM PROC2
        WHERE C = (SELECT AVG(C) FROM PROC2);
exit;
$ DROP WHERE_GDB:sp1.gdb 
