
$GBAK -r sp1.gbk WHERE_GDB:sp1.gdb

>> proc_isql_15.sql
set term go;
create procedure proc_insert (a char(5), b char(20), c char(6), d smallint, e char(15)) as
begin
insert into p values (:a, :b, :c, :d, :e);
end
go
set term ; go
set echo;
select * from p;
EXECUTE PROCEDURE PROC_INSERT 'P7', 'Widget', 'Pink', 23, 'Hoboken';
select * from p;
exit;

$ISQL -m WHERE_GDB:sp1.gdb -e -i proc_isql_15.sql
$DROP WHERE_GDB:sp1.gdb
$DELETE proc_isql_15*
