
$ GBAK -r sp1.gbk WHERE_GDB:sp1.gdb

>> proc_isql_18.sql
set term go;
create procedure  proc_select_insert as
begin
    insert into sp(sno)
    select sno from s where sno NOT IN
    (select sno from sp) ;
end
go
set term ; go
select * from sp;
EXECUTE PROCEDURE PROC_SELECT_INSERT;
select * from sp;
rollback;
select * from sp;
select * from proc_select_insert;
select * from sp;
exit;

$ ISQL -m WHERE_GDB:sp1.gdb -e -i proc_isql_18.sql
$ DROP WHERE_GDB:sp1.gdb 
$DELETE proc_isql_18*
